### PR TITLE
Update to 7.9.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.9.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by ScrewTSW** [comment]
[test]

**Comment by Katka92** [comment]
This test is failing because it needs fixes that were introduced for 7.8.0 but were not merged yet.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Test failed because the workspace was not able to start at all. For the whole test scenario, it was just in the STARTING phase. There are several errors in events [1]. I'll try to rerun tests. 
[1] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/2251/events_report.txt

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 are there test issue and suite need to be adjusted for the latest che version?

**Comment by Katka92** [comment]
The next run failed on the same problem. I tried to run Java Vertx manually there and I got `Error: Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspacezgjkr93wi9wbcwb2' reached timeout"`. 
I'm able to start a GO workspace too. That doesn't seem to be test issue.

**Comment by ibuziuk** [comment]
@Katka92 any openshift events?

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Openshift events can be found in artifacts - just click the link in a PR check report, you can see txt file with events there. I didn't gather events from my tries but they were quite similar to what is in the report.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
Workspace startup is failing with the following error:

```Error: Error response from daemon: create 4d0496474e23b6248f552fe80f5b5018cfc745c373aaaf36fc133a9b0276a616: error while creating volume path '/var/lib/docker/volumes/4d0496474e23b6248f552fe80f5b5018cfc745c373aaaf36fc133a9b0276a616/_data': mkdir /var/lib/docker/volumes/4d0496474e23b6248f552fe80f5b5018cfc745c373aaaf36fc133a9b0276a616: permission denied```

image

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW could you please try to repro with the test accounts against this PR ?

**Comment by Katka92** [comment]
@ibuziuk I can see the same problem with the test user that is used for PR check. The weird thing is that my log continues even after this failure.


Screenshot from 2020-02-21 11-13-09

**Comment by ibuziuk** [comment]
ok, looks like a blocker :/
need to investigate the root cause

**Comment by Katka92** [comment]
@ibuziuk Just to have complete information here - after a long time when workspace startup really fails, this is was is in the output:
Screenshot from 2020-02-21 13-01-28

**Comment by dmytro-ndp** [comment]
@ibuziuk, @l0rd: if [start workspace error](https://github.com/redhat-developer/rh-che/pull/1781#issuecomment-589173166) is a blocker for upstream Eclipse Che 7.9.0 release - it would be nice to have an issue with details, proper labels etc.

**Comment by ibuziuk** [comment]
@dmytro-ndp this is not a blocker for upstream release if it does not affect upstream - please continue the release process if this issue is not reproducible against vanilla 7.9.0-SNAPSHOT. We would likely need a respin, but this should not affect the current release

**Comment by dmytro-ndp** [comment]
@ibuziuk: thank you for answer!

**Comment by ibuziuk** [comment]
Issue has been created - https://github.com/eclipse/che/issues/16112

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
During the workspace startup, the `Application not available` appeared. I'll rerun tests again.

image

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
In the last test, IDE didn't load. This issue is not related to my last changes. I'll re-run the tests.

image

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
