### PR TITLE
Updating rh-che to the latest '7.3.0' version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the latest '7.3.0' version

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14656

### How have you tested this PR?
PR check CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@amisevsk for UD I got `No upstream changes detected.` but would appreciate double-checking from you

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
Test failed on LS and Build&Run commands. I'll investigate further.

**Comment by Katka92** [comment]
Tests are currently failing on: ` Plugins installation process failed. Error: Plugin broking process for workspace workspacexxaeqtgbuy09cicy failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.prod-preview.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml': Downloading https://che-plugin-registry.prod-preview.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml failed. Status code 404. `

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
When trying manually I can see this message: `rror: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspaceyn4tiynt0yjtho4f.maven-d55dc849-t6tjz" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=5174m,limits.memory=2779021312, used: limits.cpu=5758m,limits.memory=3093594112, limited: limits.cpu=6,limits.memory=3Gi', 'workspaceyn4tiynt0yjtho4f.maven-d55dc849'"`

**Comment by amisevsk** [comment]
Retested just now, and it appears the LS problem is mysteriously gone, but https://github.com/eclipse/che/issues/14724 is still present.

**Comment by amisevsk** [comment]
[test]

**Comment by Katka92** [comment]
Verified - tests are fixed. LS related tests are failing as expected.

**Comment by amisevsk** [comment]
Need to port changes from https://github.com/eclipse/che/pull/14541 to this branch

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
@sleshchenko Could you please check commit https://github.com/redhat-developer/rh-che/pull/1626/commits/b85c4fabfb9a40455b391b08eaaf28c6722fdb1e in this PR? I want to make sure I'm not missing a change coming from https://github.com/eclipse/che/pull/14541. In particular, I think the `list` API call will be broken (but is also not used) currently.

**Comment by amisevsk** [comment]
CI failed due to dockerhub outage: https://status.docker.com/pages/533c6539221ae15e3f000031

**Comment by amisevsk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
Starting a workspace fails due to 7.3.0 plugins not being included in plugin registry (che-theia + che-machine-exec). @ibuziuk WDYT about updating prod-preview registry to 7.3.0? This would likely break the preview deployment.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
plugin & devifle registries have been updated to the latest (7.3.0) version on prod-preview

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
tested on dev-cluster and after registries updates the workspace startup seems to work just fine.
test CI is failing though - https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1911/console 

> Error response from daemon: manifest for quay.io/openshiftio/rhchestage-rh-che-e2e-tests:7.3.0 not found: manifest unknown: manifest unknown
> RH-Che test image with tag 7.3.0 found on docker. Reusing image.
> Unable to find image 'quay.io/openshiftio/rhchestage-rh-che-e2e-tests:7.3.0' locally
> docker: Error response from daemon: manifest for quay.io/openshiftio/rhchestage-rh-che-e2e-tests:7.3.0 not found: manifest unknown: manifest unknown.
> See 'docker run --help'.
> Running functional tests lasted 25 seconds.
> Archiving artifacts from  for devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1911
> -rw-r--r--. 1 1009 1009 14 Oct 21 16:11 ./artifacts.key
> cp: cannot stat ‘./logs/*.log’: No such file or directory
> cp: cannot stat ‘./logs/artifacts/screenshots/’: No such file or directory
> cp: cannot stat ‘./logs/artifacts/failsafe-reports/’: No such file or directory
> sending incremental file list
> 

@Katka92 could you please take a look

**Comment by Katka92** [comment]
Tests are failing on build&run command, which is a test issue (quick fix is to change command label). The second problem is with LS verification, but when tested manually, it seems like LS is working correctly for Java Maven and Java Vert.x stacks. Approving a merge in this state. I'll provide PR with a fix later.

**Pull request merged**
