### PR TITLE
rh-che #1716 Checking the maven version for debugging the test issue

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
 Checking the maven version for debugging the test issue

### What issues does this PR fix or reference?
#1716

### How have you tested this PR?
PR check test

### CODE REVIEW

**Comment by ibuziuk** [comment]
@Katka92 any ideas about the last failure - https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/2057/consoleFull ?

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 any ideas about 

> driver/ContainerInitializer.ts(26,67): error TS2345: Argument of type 'typeof RhCheTestWorkspaceUtils' is not assignable to parameter of type 'new (...args: any[]) => ITestWorkspaceUtil'.
>   Type 'RhCheTestWorkspaceUtils' is missing the following properties from type 'ITestWorkspaceUtil': cleanUpAllWorkspaces, getIdOfRunningWorkspaces
> utils/RhCheTestWorkspaceUtils.ts(18,14): error TS2420: Class 'RhCheTestWorkspaceUtils' incorrectly implements interface 'ITestWorkspaceUtil'.
>   Type 'RhCheTestWorkspaceUtils' is missing the following properties from type 'ITestWorkspaceUtil': cleanUpAllWorkspaces, getIdOfRunningWorkspaces

**Comment by Katka92** [comment]
@ibuziuk Test tried to rebuild tests depending on the newest upstream image. That caused this problem. I'll take a look at why it happened. But your change has failed too: `.ci/functional_tests_utils.sh: line 128: mvn: command not found`. Please try something like `version=$(scl enable rh-maven33 "mvn -v"`.

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 could you please take a look at the pr check failures  

> Processing che plugin registry yaml
> jq: error: syntax error, unexpected IDENT, expecting ';' or ')' (Unix shell quoting issues?) at <top-level>, line 1:
> .parameters = (.parameters | map((select(.name == "IMAGE_TAG") | .value) |= "Apache Maven 3.3.9 (Red Hat 3.3.9-2.8) Maven home: /opt/rh/rh-maven33/root/usr/share/maven Java version: 1.8.0_232, vendor: Oracle Corporation Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "3.10.0-1062.9.1.el7.x86_64", arch: "amd64", family: "unix" 7.3.2"))                                                                      

looks like some parsing issue

**Comment by Katka92** [comment]
@ibuziuk Heh, it took me a while. The problem is here: https://github.com/redhat-developer/rh-che/pull/1746/files#diff-49ec81ac18e778ae14373403d549667fR122. This function is returning a string which should contain the maven version. But as this line was added here, it is echoing the `mvn -v` - so it means it returns all the info about maven. This is exactly what is then used as a version. I think the solution should be to use that method separately, not inside a `getVersionFromPom`.

**Comment by Katka92** [comment]
@ibuziuk Now the output is correct:
```
Installing all dependencies lasted 217 seconds.
Apache Maven 3.3.9 (Red Hat 3.3.9-2.8) Maven home: /opt/rh/rh-maven33/root/usr/share/maven Java version: 1.8.0_232, vendor: Oracle Corporation Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "3.10.0-1062.9.1.el7.x86_64", arch: "amd64", family: "unix"
Running devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io PR: #1746, build number #2062 for che-version:7.3.2
```
Maybe we can add some "header" to the `mvn -v` output so it is more clear for somebody who is reading the logs.

**Comment by Katka92** [comment]
@ibuziuk Test failed on known issue https://github.com/redhat-developer/rh-che/issues/1744. I'm OK with merging or if you want, you can re-run.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 nice catch with version, but I want all tests to e green before merging

**Pull request merged**
