### PR TITLE
Updating rh-che to the 7.0.0-beta-2.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the 7.0.0-beta-2.0 upstream version

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1261

### How have you tested this PR?
supposed to be tested via CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
ah, there is no way to change normal PR to draft after creation for now - https://dev.to/park53kr/comment/8mm7
opt for good old WIP

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 any ideas about:

> [ERROR]   BuildAndRunProjectTest.checkWorkspace » Provision Unable to provision, see the...
> [INFO] 
> [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk The user can not start workspace. There is an error in log: ```Workspace with name='workspace649jxp' id='workspacezeejujja4ztvflqz' start failed.``` It seems similar like problems we have in periodic jobs. I'll take a look closer and I'll try to start workspace manually. I'll provide more info later.

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
From quick look it is not problem as we have in periodic tests. User used in PR check is able to start workspace from other PRs. I'll investigate if there is problem with this PR or with namespace on dev cluster. Once I have more info I'll reach you here.

**Comment by Katka92** [comment]
There is a failure from the last build in rh-che log [1]. I'm trying that with my own account on the same rh-che deployment. 

[1]
Screenshot from 2019-03-18 14-22-49

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
I have a same message with my own account ```kkanova-preview``` [1]. I've tried that account on prod-preview and I'm able to start workspace here. Are you sure that this is problem in PR check or infra and not in Rh-che build? I'm not much familiar with that failure, could you please have a look on that? Do you have any idea?

[1] 
Screenshot from 2019-03-18 14-30-43

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk There are some errors in logs when rh-che is starting [1]. Could you please verify that this is not related to the problem with starting workspace?

[1]
```
2019-03-18 16:53:19,557[ost-startStop-1]  [ERROR] [io.sentry.SentryClientFactory 75]    - Error creating valid DSN from: 'NULL'.
io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'


2019-03-18 16:53:34,676[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 144]   - Failed to load stack icon data for the stack with id 'simple-theia'
java.io.IOException: Not found resource: stacks-images/type-theia.svg


2019-03-18 16:53:35,093[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 144]   - Failed to load stack icon data for the stack with id 'ceylon-java-javascript-dart-centos'
java.io.IOException: Not found resource: stacks-images/type-ceylon.svg

2019-03-18 16:53:35,142[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 101]   - Failed to store stacks from 'che-in-che.json'

```

**Comment by ibuziuk** [comment]
@Katka92 the logs above are not related to workspace startup failures

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk I've created image with version changed to beta-2 snapshot and deployed it on dev cluster. You can try it manually here [1]. I got the same error as in your PR (I've tried two accounts). 
I deployed master version of rh-che with beta-1 version here [2]. I was able to start workspace without any problems.
I've tried to deploy upstream che (version 7.0.0-beta-2.0-SNAPSHOT) on minishift by running script deploy_che.sh and I was not able to reproduce that - workspace started correctly. 
I think that the reason why your PR is failing is that change of version.

[1] http://rhche-ilya.devtools-dev.ext.devshift.net/
[2] http://rhche-beta1.devtools-dev.ext.devshift.net

**Comment by ibuziuk** [comment]
@Katka92 thanks for investigations, really valuable input. Looks like PR check caught a regression related to `exec` functionality

**Comment by amisevsk** [comment]
The log message is slightly deceptive -- looks like the actual error comes from the Kubernetes client [failing to create a websocket connection](https://github.com/fabric8io/kubernetes-client/blob/1724b946300d824c6378c0f596bed1f826164ba5/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L201) for one of the watches we do during start. I suspect it's related to infra issues.

**Comment by Katka92** [comment]
@amisevsk Interesting, so there was some change in a way of creating the connection? I thought it is not infra related because it affects only one version - beta-2 which is failing 100% on that and I've never seen that error in earlier version.

**Comment by amisevsk** [comment]
I honestly have no idea -- nothing should be different here from a previous version. I only assumed it's infra-related because that's kind of the flakiest factor for us.

I can take a better look at it.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
hmm.. was able to repro the same issue against free-stg, which should not have any infra issues afaik:

image


> 2019-03-23 22:14:47,681[penshift.io/...]  [WARN ] [k.c.d.i.WatchConnectionManager 201]  - Exec Failure
> --
>   | java.io.EOFException: null
>   | at okio.RealBufferedSource.require(RealBufferedSource.java:60)
>   | at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
>   | at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
>   | at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
>   | at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
>   | at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
>   | at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
>   | at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
>   | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>   | at java.lang.Thread.run(Thread.java:748)
>   | 2019-03-23 22:16:02,124[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 242]  - Failed to start Kubernetes runtime of workspace workspaceb3cmnd7yympzfuyt. Cause: Waiting for Kubernetes environment 'default' of the workspace'workspaceb3cmnd7yympzfuyt' reached timeout

This starting to look more and more like a regression / incompatibility with upstream thingy.

**Comment by ScrewTSW** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
please do not merge until cms are updated on dsaas / dsaas-stg

**Comment by ibuziuk** [comment]
cm has been updated on prod-preview - https://gitlab.cee.redhat.com/service/app-interface/merge_requests/251/ - we are good to merge now

**Pull request merged**
