### PR TITLE
Updating rh-che to the latest `7.1.0` upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the latest `7.1.0` upstream version

### What issues does this PR fix or reference?
 #1573

### How have you tested this PR?
PR check CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
> Archiving artifacts lasted 1 seconds.
> Tests result: FAILURE
> + echo 'Che functional tests failed. Error code:125'
> Che functional tests failed. Error code:125

@Katka92 @ScrewTSW could you please take a look

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Seems like a problem with pulling docker image. I'll fix that.

**Comment by ibuziuk** [comment]
@Katka92 PR updated to `7.1.0` but tests are still failing:

> Tests result: FAILURE
> + echo 'Che functional tests failed. Error code:1'
> Che functional tests failed. Error code:1
> + exit 4
> Connection to 172.19.3.80 closed.
> + rtn_code=4
> + '[' 4 -eq 0 ']'
> + [[ 4 -eq 124 ]]
> + curl 'http://admin.ci.centos.org:8080/Node/fail?key=8dc1a710-6097-11e6-a671-525400ea212d&ssid=a5d771c2'

**Comment by Katka92** [comment]
The fixes of this PR were not merged, they are still in a PR to this branch and they are still in progress. But update to 7.1.0 seems to be broken, I'm not able to start any workspace:
Screenshot from 2019-09-06 07-53-28

**Comment by Katka92** [comment]
[test]

**Pull request merged**
