### PR TITLE
Updating to the latest `7.0.0-RC-2.0` upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating to the latest `7.0.0-RC-2.0` upstream version

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1444

### How have you tested this PR?
PR check against dev cluster

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW looks like there were changes in upstream and RC2 update started to fail:

> [INFO] Compiling 6 source files to /root/payload/functional-tests/target/test-classes
> warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.8'
> /root/payload/functional-tests/src/test/java/com/redhat/che/functional/tests/Che7DialogAbout.java:124: error: cannot find symbol
>     newWorkspace.clickOnAllStacksTab();
>                 ^
>   symbol:   method clickOnAllStacksTab()
>   location: variable newWorkspace of type NewWorkspace
> /root/payload/functional-tests/src/test/java/com/redhat/che/functional/tests/Che7DialogAbout.java:131: error: cannot find symbol
>       newWorkspace.setMachineRAM("dev-machine", machineRam);
>                   ^
>   symbol:   method setMachineRAM(String,Double)
>   location: variable newWorkspace of type NewWorkspace
> 2 errors
> 1 warning

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
@ibuziuk Note that before merging this PR we should double check upstream dashboard changes; we're currently overriding upstream functionality in an unintended way -- I'll take a closer look.

**Comment by amisevsk** [comment]
I've added a commit to adapt upstream devfile changes to this PR, but haven't had a chance to test it much. The relevant upstream PR: https://github.com/eclipse/che/pull/13469

**Comment by ibuziuk** [comment]
@amisevsk good point. My plan was:
- wait for RC 1.1 release - https://github.com/eclipse/che/issues/13553
- update prod / prod-preview to RC 1.1
- merge this PR and update prod-preview only to RC 2 to have the latest / greatest Che for testing
- update prod to RC2 (or GA) version once the docs are ready, devfiles from devfile registry reliably work and getting started factories are replaced with dedicated devfiles

**Comment by amisevsk** [comment]
[test]

**Comment by amisevsk** [comment]
@ibuziuk Build is succeeding and dashboard is updated.

**Comment by amisevsk** [comment]
Looks like there are some dashboard issues: The "servers", "env vars", and "volumes" tabs shouldn't be there AFAIK, and show 

Screenshot from 2019-06-20 17-34-40

**Comment by ibuziuk** [comment]
Prod is updated to CR 1.1 - so we are ready to promote CR 2 to prod-preview

**Comment by ibuziuk** [comment]
@rhopp @Katka92 so, looks like che 7 tests are using dashboard UI:

> Caused by: org.openqa.selenium.NoSuchElementException: 
> no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-stack-id='che7']"}

I believe the PR check tests need to be updated to use new devfile based apporach

**Comment by ibuziuk** [comment]
[test}

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Once this PR is merged, tests against production will fail due to the change in test. If the update on production will come e.g. next day after update on prod-preview, I think we can be OK with that. If you expect few days between updating prod-preview and prod, I would assume to add switch to the test.

**Comment by ibuziuk** [comment]
@Katka92 we will update prod only with GA version, so in the meantime, I would propose to merge this PR and start testing the latest version of upstream Che ASAP and adjust prod test suite to use stacks

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW what is the test prod-preview issue?

**Comment by Katka92** [comment]
@ibuziuk Sorry, my fault, I fixed my comment.

**Comment by ibuziuk** [comment]
@Katka92 ok, but is it a blocker for merging the PR. We could simply merge and fix the prod periodic tests separately?

**Comment by Katka92** [comment]
Sure, that's why I wrote +1 for merging that PR. I hope that tomorrow we will have PR with the fix merged, so we will loose only 1 day of reports.

**Pull request merged**
