### PR TITLE
WIP: Switching build bethod to docker dependency image based

### PR DESCRIPTION
**Pull request by ScrewTSW**
### What does this PR do?
This PR removes the old logic from PR-Check script where the docker image used to be built directly on the node, now the build happens in a pre-configured docker image

### What issues does this PR fix or reference?
-

### How have you tested this PR?
manual testing

### CODE REVIEW

**Comment by ibuziuk** [comment]
@ScrewTSW can we close this PR ?

**Comment by ibuziuk** [comment]
@ScrewTSW @tdancs  can we close this PR ? or are you planning to finalize it?

**Comment by ibuziuk** [comment]
the PR was opened almost 2 months ago and there is no activity recently

**Comment by ScrewTSW** [comment]
Closing because the dependency image builds are in a broken state.

**Pull request closed without merging**
