### PR TITLE
Updating rh-che to the latest 7.0.0-beta-1.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the latest `7.0.0-beta-1.0` upstream version

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1254

### How have you tested this PR?
CI PR check

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@ScrewTSW @Katka92 @rhopp could you please take a look at the test results ? https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1202/console 
it is still `You are not allowed to start more workspaces.` do we have an issue for that on QA side ?

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
