### PR TITLE
Add FAQ button to dashboard which points to documentation in rhche

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Adds FAQ link to user dashboard. Draft PR until actual doc is written; currently just points to the dev guide.

FAQs-link

### What issues does this PR fix or reference?
#1287

### How have you tested this PR?
Locally on minishift

### CODE REVIEW

**Comment by garagatyi** [comment]
This pull request **introduces 3 alerts** when merging abad8af7ec66fb0a3168a4a9b76381ec0968eff3 into ff6ef79452616fc39aef3dd9daa890e06e4be61f - [view on LGTM.com](https://lgtm.com/projects/g/redhat-developer/rh-che/rev/pr-1f278493c15c9a2ce32333095075ff7ad6f5a521)

**new alerts:**

* 3 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
Tests are failing because there is a missing header in file ```che-footer.html```. Please fix that before running tests again.

```
[WARNING] Unknown file extension: /root/payload/assembly/fabric8-ide-dashboard-war/src/app/workspaces/create-workspace/create-workspace.styl
[WARNING] Unknown file extension: /root/payload/assembly/fabric8-ide-dashboard-war/src/app/workspaces/share-workspace/share-workspace.styl
[WARNING] Missing header in: /root/payload/assembly/fabric8-ide-dashboard-war/src/components/widget/footer/che-footer.html
```

**Comment by amisevsk** [comment]
Hm, funny -- none of the upstream `.html` files have license headers. I'll fix.

**Comment by amisevsk** [comment]
Added license header -- thanks @Katka92

**Comment by garagatyi** [comment]
This pull request **introduces 3 alerts** when merging efad38067cbec0d5fef07e5c1474aaafba1bc3d0 into ada7b263df400dcd39206973696b900ae32efddd - [view on LGTM.com](https://lgtm.com/projects/g/redhat-developer/rh-che/rev/pr-56ad0301ccb78f08200ca9adcc861166c15e47a2)

**new alerts:**

* 3 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ibuziuk** [comment]
PR with FAQ.adoc - https://github.com/redhat-developer/rh-che/pull/1324

**Comment by ibuziuk** [comment]
@amisevsk I guess we can simply change the link to https://github.com/redhat-developer/rh-che/blob/master/FAQ.adoc and merge. wdyt ?

**Comment by amisevsk** [comment]
Yeah, sounds good. On it.

**Comment by amisevsk** [comment]
Updated link to point at correct FAQ doc, and fixed the complaints from the robot (although those were for upstream code).

PR should be ready to review/merge.

**Pull request merged**
