### PR TITLE
Update to 7.24.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.24.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

Related issue - https://github.com/eclipse/che/issues/18725

### CODE REVIEW

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2026.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
@ScrewTSW 7.24.0 pre-release is failing on the scala & quarkus:
```
144 passing (48m)
  2 pending
  2 failing
```
It would be great to address for `7.24.0`:

- eclipse/che#18662
- eclipse/che#18663

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2026.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
[test]

**Comment by tomgeorge** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2026.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
Pre-release tests results:
 
```
144 passing (44m)
  2 pending
  2 failing
```

Known issues for the failing tests:
 - https://github.com/eclipse/che/issues/18663
 - https://github.com/eclipse/che/issues/18662

**Review by ibuziuk — APPROVED** [review]

**Review by Katka92 — APPROVED** [review]

**Pull request merged**
