### PR TITLE
[DO NOT MERGE] Test 7.15.1 on prod-preview

### PR DESCRIPTION
**Pull request by Katka92**
Do not merge, PR servers for testing 7.15.1.

### CODE REVIEW

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io
[pre-release-tests]

**Comment by ibuziuk** [comment]
@Katka92 IMO it would be more consistent to test the pre-realse against saas-openshiftio

**Comment by Katka92** [comment]
@ibuziuk So you mean it's better to create this dummy DO NOT MERGE request in saas-openshiftio, right? Another way is to test prod-preview in 7.16.0 branch.

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io
[pre-release-tests]

**Comment by ibuziuk** [comment]
> @ibuziuk So you mean it's better to create this dummy DO NOT MERGE request in saas-openshiftio, right? Another way is to test prod-preview in 7.16.0 branch.

@Katka92 no, not dummy - https://github.com/openshiftio/saas-openshiftio/pull/1441

**Comment by Katka92** [comment]
Aaa, I see :D Ok, you're right. Closing this PR.

**Pull request closed without merging**
