### PR TITLE
Update to 6.18.0

### PR DESCRIPTION
**Pull request by fabric8cd**
Tracking changes for fixing compatibility with upstream 6.18.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by Katka92** [comment]
Testing curl command from local terminal.

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/1040/console

**Comment by ibuziuk** [comment]
[test]

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/96/console

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/99/console

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/100/console

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/102/console

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/103/console

**Pull request closed without merging**
