### PR TITLE
rh-che #1412 Updating to the latest 7.0.0-RC-1.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating to the latest 7.0.0-RC-1.0 upstream version

### What issues does this PR fix or reference?
#1412

### How have you tested this PR?
N/A

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@skabashnyuk do you happen to know if we still need a workaround with jar skipping on our end in CR1 https://github.com/redhat-developer/rh-che/commit/36897e44733617b0e0d48da40e07c97c96c39f39#diff-d79082aaff35c41c21db3933361c39efR148 ?

**Comment by skabashnyuk** [comment]
Yes. you need to do that. fix are not merged yet https://github.com/eclipse/che/pull/13464

**Comment by ibuziuk** [comment]
@skabashnyuk thanks for the clarification. Created https://github.com/redhat-developer/rh-che/issues/1442 for following up on this

**Comment by ibuziuk** [comment]
@Katka92 @tdancs could you please take a look at the `[INFO] functional-tests ................................... FAILURE [02:15 min]`

````
[ERROR] Failed to execute goal on project functional-tests: Could not resolve dependencies for project com.redhat.che:functional-tests:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.che.selenium:che-selenium-core:jar:7.0.0-RC-1.0 -> org.seleniumhq.selenium:selenium-api:jar:3.0.1: Failed to read artifact descriptor for org.seleniumhq.selenium:selenium-api:jar:3.0.1: Could not transfer artifact org.seleniumhq.selenium:selenium-api:pom:3.0.1 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.248.215] failed: Connection timed out (Connection timed out) -> [Help 1]
````

**Comment by ibuziuk** [comment]
hmm, builds fine locally...
[test]

**Pull request merged**
