### PR TITLE
Fix #124 by selecting the stack policy for loading the content of stack.json

### LINKED ISSUE #124: [Rebase oscon] Adapt new stacks.json to the new policy change
see - https://issues.jboss.org/browse/CHE-298

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Policy on loading stacks has been changed. In order to keep previous policy, a flag needs to be set

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/124

#### Changelog
Update policy for loading stacks.json file

### CODE REVIEW

**Comment by benoitf** [comment]
@sunix move PR from master to rebased branch
but you'll still require https://github.com/fabric8io/fabric8-online/pull/252 as well

**Comment by sunix** [comment]
ok in this branch we have our custom stacks.json, would you add the new way to include it in the same PR or another one ?

**Comment by davidfestal** [comment]
did you do the corresponding change in `fabric8-online` to create, in the Che deployment, the env variable that takes its value in this config map value ?

**Comment by benoitf** [comment]
@davidfestal yes there is a PR as well

**Comment by benoitf** [comment]
@sunix  it should use the dame location of the file as before

**Comment by sunix** [comment]
ok let's try with this then :)

**Comment by sunix** [comment]
@davidfestal https://github.com/fabric8io/fabric8-online/pull/252

**Pull request merged**
