### PR TITLE
Bump to che version 5.21.0

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?
Update the version of `eclipse/che` to the latest release (`v.5.21.0`)

### CODE REVIEW

**Comment by ibuziuk** [comment]
@l0rd @rhopp PR verification is disabled ?

**Comment by rhopp** [comment]
[test]

**Comment by ibuziuk** [comment]
```
[ERROR]   The project  (/root/payload/pom.xml) has 1 error
[ERROR]     Non-parseable POM /root/payload/pom.xml: unexpected character in markup < (position: END_TAG seen ...<groupId>org.eclipse.che</groupId>\n<<... @19:3)  @ line 19, column 3 -> [Help 2]
[ERROR] 
```

**Comment by ibuziuk** [comment]
@rhopp look like smth. is wrong with PR checkout - is it supposed to work only for multi-tenant branch ?

`Applying: First working version of `rh-che` based on the upstream `ch-multiuser`
`

This PR is for master though ^


```
Complete!
+ checkoutIfPR
+ cat jenkins-env
+ grep -E '(ghprbSourceBranch|ghprbPullId)='
+ sed 's/^/export /g'
+ source /tmp/jenkins-env
++ export ghprbPullId=464
++ ghprbPullId=464
++ export ghprbSourceBranch=bump-to-version-5.21.0
++ ghprbSourceBranch=bump-to-version-5.21.0
+ [[ ! -z 464 ]]
+ [[ ! -z bump-to-version-5.21.0 ]]
+ set +x
Checking out to Github PR branch.
remote: Counting objects: 3, done.        
remote: Compressing objects:  50% (1/2)           
remote: Compressing objects: 100% (2/2)           
remote: Compressing objects: 100% (2/2), done.        
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0        
Unpacking objects:  33% (1/3)   
Unpacking objects:  66% (2/3)   
Unpacking objects: 100% (3/3)   
Unpacking objects: 100% (3/3), done.
From https://github.com/redhat-developer/rh-che
 * [new ref]         refs/pull/464/head -> bump-to-version-5.21.0
Previous HEAD position was d8655d6... Bump to version 5.21.0
Switched to branch 'bump-to-version-5.21.0'
From https://github.com/redhat-developer/rh-che
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Fix buggy script
Using index info to reconstruct a base tree...
M	dev-scripts/local_docker_create_images_and_tag.sh
Falling back to patching base and 3-way merge...
Auto-merging dev-scripts/local_docker_create_images_and_tag.sh
Applying: First working version of `rh-che` based on the upstream `ch-multiuser`
Using index info to reconstruct a base tree...
M	assembly/assembly-ide-war/src/main/patches/src/main/webapp/META-INF/context.xml.patch
M	assembly/assembly-main/pom.xml
M	assembly/assembly-wsagent-server/pom.xml
M	assembly/assembly-wsagent-war/pom.xml
A	assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/RedHatCheWsAgentServletModule.java
A	assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/WsAgentModule.java
M	assembly/assembly-wsmaster-war/pom.xml
M	assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
M	assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterServletModule.java
M	assembly/user-auth-valve/src/main/java/com/redhat/che/valve/UserAuthValve.java
M	pom.xml
<stdin>:192: trailing whitespace.
                    
<stdin>:194: trailing whitespace.
                    
warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml

```

**Comment by rhopp** [comment]
The opposite.. It works only for PR to master. This one is against multitenant branch.
Theoretically I could change jobs configuration to be able to run PR check against any branch, but because we still don't have environment to deploy che-multitenant just for PR check I didn't want to invest time into this (almightly jobs yaml is a mess :disappointed:)
The error you copied here is right... It tries to rebase this PR onto master (which fails).

**Comment by ibuziuk** [comment]
yeah, I think we need a test-mt che-server for verifying PRs against `multi-tenant-rh-che` and once migration is done `master`

**Pull request merged**
