### PR TITLE
Fix location of rb.yml file

### PR DESCRIPTION
**Pull request by msrb**
Signed-off-by: Michal Srb <michal@redhat.com>

### CODE REVIEW

**Comment by msrb** [comment]
I am not 100% sure about this, but there is no `rb.yml` in https://github.com/fabric8io/fabric8-online/tree/master/apps/che/src/main/fabric8.

With this change I was able to deploy Che on minishift.

**Comment by l0rd** [comment]
@msrb rb.yml was moved 2 days ago to that location.
LGTM

**Comment by l0rd** [comment]
@amisevsk I can't see any issue. I think @rawlingsj moved RoleBinding in `packages` folder to make it consistent with other apps.

**Comment by amisevsk** [comment]
LGTM then, +1 to merge

**Pull request merged**
