### PR TITLE
Move to upstream 6.13.0

### PR DESCRIPTION
**Pull request by amisevsk**

### CODE REVIEW

**Comment by amisevsk** [comment]
Rebase onto current master.

**Comment by amisevsk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
I've tried to fix the unit tests broken by the Mockito change. 

At this point compilation still fails in functional tests, and I'm not sure how to fix those.

cc: @rhopp

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
With formatting fix, maven build succeeds locally.

**Comment by ibuziuk** [comment]
@amisevsk @rhopp I think we could now remove the snapshot from pom and WIP form description so that it would be ready to be merged. Hopefully the update should fix https://github.com/openshiftio/openshift.io/issues/4391 which breaks e2e flow on prod-preview

**Pull request merged**
