### PR TITLE
che #15182 Updating rh-che to the 7.3.2 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the 7.3.2 upstream version

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15182

### How have you tested this PR?
PR-check CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
Looks like we do not need to backport any UD changes from  -https://github.com/eclipse/che/pull/15194/files
```
[ibuziuk@fedora rh-che]$ ./dev-scripts/check-upstream-dashboard.sh 7.3.2
Testing update to version 7.3.2
Getting dashboard source diff for current Che parent version
     [exec] Result: 1
Updating parent version in pom.xml to 7.3.2
Getting dashboard source diff for Che parent version 7.3.2
     [exec] Result: 1
No upstream changes detected.
Executing cleanup
```

**Comment by ibuziuk** [comment]
@ScrewTSW looks like the PR check is still deploying 7.3.1 version of the registry - http://che-plugin-registry-prcheck-1696.devtools-dev.ext.devshift.net/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/ This currently breaks the test verification

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
> @ScrewTSW looks like the PR check is still deploying 7.3.1 version of the registry - http://che-plugin-registry-prcheck-1696.devtools-dev.ext.devshift.net/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/ This currently breaks the test verification

should be fixed with !1700

**Comment by amisevsk** [comment]
```
Testing update to version 7.3.2
Getting dashboard source diff for current Che parent version
     [exec] Result: 1
Updating parent version in pom.xml to 7.3.2
Getting dashboard source diff for Che parent version 7.3.2
     [exec] Result: 1
No upstream changes detected.
Executing cleanup
```

**Comment by ibuziuk** [comment]
@amisevsk thanks for double-checking :+1:

**Pull request merged**
