### PR TITLE
rh-che #395: Fixing build: unbound variable: DEVSHIFT_TAG_LEN / DEVSH…

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Trying to fix - https://ci.centos.org/view/Devtools/job/devtools-build-run-che-build-multi-tenant-rh-che/14/console

```
.ci/cico_deploy.sh: line 45: DEVSHIFT_TAG_LEN: unbound variable
.ci/cico_deploy.sh: line 55: DEVSHIFT_REGISTRY: unbound variable
```

### What issues does this PR fix or reference?

#395 

### How have you tested this PR?
Not tested

### CODE REVIEW

**Comment by ibuziuk** [comment]
@benoitf thanks, but before merging the job template [1] needs to be updated. 
@vpavlin will be able to help with template setup so that the current job [2] would not only build images but would also deploy to prod-preview (currently deployment would fail until template is merged but for the first step I think it is fine)

[1] https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml#L947
[2] https://ci.centos.org/view/Devtools/job/devtools-build-run-che-build-multi-tenant-rh-che/
[3] https://github.com/redhat-developer/rh-che/pull/407

**Comment by vpavlin** [comment]
@ibuziuk New tempaltes are in place

https://github.com/almighty/almighty-jobs/pull/376

Jobs:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-build-che-credentials-master/
https://ci.centos.org/view/Devtools/job/devtools-rh-che-build-che-credentials-multi-tenant-rh-che/

You'll need to add service yamls to https://github.com/openshiftio/saas-openshiftio so that CI can find templates and deploy

**Comment by vpavlin** [comment]
One problem that we might encounter is that master and multi-tenant builds will be both deployed, which we probably don't want...I assume only multi-tenant one should be deployed to rh-idev - let me know if this is correct assumption and I'll fix the job

**Comment by ibuziuk** [comment]
@vpavlin assuming that we are very likely going to have canary rollout we do want both master and multi-tenant builds being deployed but differently and only :

1. fabric8-tenant-che [1] will be working as it works right now - new versions will be promoted to user tenant on openshift online powered by fabric8-tenant once we push to rh-che master (so, I would not modify master job at all right now) 
2. rh-che from `multi-tenant-rh-che` branch will be deployed to dedicated prod / prod-preview 

> I assume only multi-tenant one should be deployed to rh-idev - let me know if this is correct assumption and I'll fix the job

So, correct only multi-tenant is supposed to be deployed on dedicated rh-idev & dsaas

[1] https://github.com/fabric8-services/fabric8-tenant-che
[2] https://github.com/fabric8-services/fabric8-tenant

**Comment by vpavlin** [comment]
ok, so with this 

https://github.com/almighty/almighty-jobs/pull/378

only multi-tenant-rh-che branch will go through deployment when job is finished.. we still need an entry in saas-openshiftio for that to succeed

**Comment by ibuziuk** [comment]
@vpavlin thanks. merging this PR and will be working on saas-openshiftio entry

**Pull request merged**
