### PR TITLE
Updating rh-che to the latest 6.18.1 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the latest 6.18.1 upstream version

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1230

### How have you tested this PR?
PR check is supposed to test it

### CODE REVIEW

**Comment by ScrewTSW** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@rhopp @tdancs PR check is still failing could you please investigate ?

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
