### PR TITLE
Use  CHE 6.12.0-SNAPSHOT.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Use  CHE 6.12.0-SNAPSHOT.

### CODE REVIEW

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
@rhopp @ScrewTSW @Katka92 can you point me to the error in the CI console? I don't understand where the error is described

**Comment by Katka92** [comment]
@garagatyi Hi, I was facing this error today too. I have a fix so I'll push it and rerun this your PR.

**Comment by garagatyi** [comment]
@Katka92 thanks!

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by rhopp** [comment]
Tests failed on workspace not being able to start. Log from che-master:
```

2018-09-21 12:35:36,790[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'rh-che-automation-preview/mmvza' with id 'workspacepl5iwf7b2wvcx3em' created by user 'rh-che-automation-preview'
--
  | 2018-09-21 12:35:37,944[nio-8080-exec-5]  [INFO ] [.c.a.w.s.w.PluginMetaRetriever 67]   - Che tooling plugins feature is disabled - Che plugin registry API endpoint property 'che.workspace.plugin_registry_url' is not configured
  | 2018-09-21 12:35:37,988[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 317]   - Starting workspace 'rh-che-automation-preview/mmvza' with id 'workspacepl5iwf7b2wvcx3em' by user 'rh-che-automation-preview'
  | 2018-09-21 12:35:39,972[aceSharedPool-0]  [WARN ] [i.f.k.c.i.VersionUsageUtils 55]      - The client is using resource type 'deployments' with unstable version 'v1beta1'
  | 2018-09-21 12:35:59,261[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`0c08fee4-5bae-4063-ad65-091bb80a9df5` env=`default` workspace=`workspacepl5iwf7b2wvcx3em` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-09-21T12:35:59.255546086Z`
  | 2018-09-21 12:39:01,451[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 221]  - Failed to start Kubernetes runtime of workspace workspacepl5iwf7b2wvcx3em. Cause: Server 'wsagent/http' in machine 'dev-machine' not available.
  | 2018-09-21 12:39:02,711[aceSharedPool-0]  [WARN ] [i.f.k.c.i.VersionUsageUtils 55]      - The client is using resource type 'replicasets' with unstable version 'v1beta1'
  | 2018-09-21 12:39:03,125[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 378]   - Workspace 'rh-che-automation-preview:mmvza' with id 'workspacepl5iwf7b2wvcx3em' start failed
```

**Comment by garagatyi** [comment]
@AndrienkoAleksandr FYI

**Comment by rhopp** [comment]
Trying to start workspace manually resulted in the same error in log.
This is from workspace startup output in browser:
image

**Comment by AndrienkoAleksandr** [comment]
@rhopp Could you provide link to the instance for me?

**Comment by rhopp** [comment]
@AndrienkoAleksandr Sorry: http://rhche-che6-automated.devtools-dev.ext.devshift.net/
For access to logs, you would need account on devtools-dev.ext.devshift.net.
Note, that the instance will run until some other PR will overwrite it (we are working on a solution for that)

**Comment by AndrienkoAleksandr** [comment]
@rhopp thanks a lot.

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
Here is the exception in wsagent:

<details>

```
2018-09-25 19:24:30,214[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4752]    - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: Can't get Che analytics settings from wsmaster
  at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.<init>(AnalyticsManager.java:132)
  at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.class(AnalyticsManager.java:75)
  while locating com.redhat.che.plugin.analytics.wsagent.AnalyticsManager
    for the 1st parameter of com.redhat.che.plugin.analytics.wsagent.AnalyticsActivityService.<init>(AnalyticsActivityService.java:40)
  at com.redhat.che.plugin.analytics.wsagent.AnalyticsWsAgentModule.configure(AnalyticsWsAgentModule.java:29)
  while locating com.redhat.che.plugin.analytics.wsagent.AnalyticsActivityService
Caused by: java.lang.RuntimeException: Can't get Che analytics settings from wsmaster
        at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.<init>(AnalyticsManager.java:140)
        at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager$$FastClassByGuice$$30cb3d0a.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ForbiddenException: This operation cannot be performed using machine token.
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:268)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
        at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.<init>(AnalyticsManager.java:135)
        ... 43 more

2) Error injecting constructor, java.lang.RuntimeException: Can't get Che analytics settings from wsmaster
  at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.<init>(AnalyticsManager.java:132)
  at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.class(AnalyticsManager.java:75)
  while locating com.redhat.che.plugin.analytics.wsagent.AnalyticsManager
Caused by: java.lang.RuntimeException: Can't get Che analytics settings from wsmaster
        at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.<init>(AnalyticsManager.java:140)
        at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager$$FastClassByGuice$$30cb3d0a.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ForbiddenException: This operation cannot be performed using machine token.
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:268)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
        at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.<init>(AnalyticsManager.java:135)
        ... 33 more

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-09-25 19:24:30,217[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5208]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2018-09-25 19:24:30,221[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5259]     - Context [] startup failed due to previous errors
2018-09-25 19:24:30,251[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/che/ws-agent/webapps/ROOT.war] has finished in [5,168] ms
2018-09-25 19:24:30,255[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-4401"]
2018-09-25 19:24:30,265[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 5379 ms
sh-4.2$
```
</details>

**Comment by garagatyi** [comment]
@ibuziuk @davidfestal so we have a change upstream that breaks wsagent in RhChe based on CHe 6.12.
[Here](https://github.com/eclipse/che/commit/01d9fc73daec7863800cf48e4a6744f43299bb91) Che platform team limited scope of allowed operations with machine token to workspace related ones only.
And [here](https://github.com/redhat-developer/rh-che/blob/936904a452a401cf0b8be4162cf16ae9a64f2f37/plugins/che-plugin-analytics/che-plugin-analytics-wsagent/src/main/java/com/redhat/che/plugin/analytics/wsagent/AnalyticsManager.java#L132) we call woopra related API.
What should we do? Can we fixed it in this sprint to unblock delivering of terminal/exec functionality in WS.NEXT to OSIO?

**Comment by davidfestal** [comment]
I created the issue https://github.com/redhat-developer/rh-che/issues/927 and will started working on it

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by rhopp** [comment]
Workspace startup fails with ```Error: Failed to run the workspace: "Server 'wsagent/http' in machine 'dev-machine' not available."```

```

2018-10-01 09:01:14,517[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 317]   - Starting workspace 'rhopp-preview/wksp-2e05' with id 'workspacens6t38hannwxlzm4' by user 'rhopp-preview'
--
  | 2018-10-01 09:01:35,914[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`214d7d57-9c96-4be6-8f25-c249aae06314` env=`default` workspace=`workspacens6t38hannwxlzm4` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-10-01T09:01:35.903478693Z`
  | 2018-10-01 09:04:39,255[aceSharedPool-3]  [WARN ] [.i.k.KubernetesInternalRuntime 220]  - Failed to start Kubernetes runtime of workspace workspacens6t38hannwxlzm4. Cause: Server 'wsagent/http' in machine 'dev-machine' not available.
  | 2018-10-01 09:04:40,567[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 378]   - Workspace 'rhopp-preview:wksp-2e05' with id 'workspacens6t38hannwxlzm4' start failed


```

**Comment by garagatyi** [comment]
@rhopp thank you, but there is no need to analyze failures in this PR. I'm playing with it to fix Workspace.NEXT flow that is not reflected in tests. I just use `[test ]` to deploy RhChe on prod preview to check my fixes

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
@AndrienkoAleksandr terminal to a machine from the dockerimage recipe works. But it doesn't work with sidecar containers. 
Here is my workspace description:
<details>

```
{
  "links": {
    "self": "http://rhche-che6-automated.devtools-dev.ext.devshift.net/api/workspace/workspace0h2a0unfrqi967tr",
    "ide": "http://rhche-che6-automated.devtools-dev.ext.devshift.net/ogaragat-preview/wksp-7svy",
    "environment/outputChannel": "ws://rhche-che6-automated.devtools-dev.ext.devshift.net/api/websocket",
    "environment/statusChannel": "ws://rhche-che6-automated.devtools-dev.ext.devshift.net/api/websocket"
  },
  "attributes": {
    "stopped_by": "activity-checker",
    "org.eclipse.che.runtimes_id": "runtimeswbf7rqgkenrt8k5d",
    "startNumber": "5",
    "created": "1538392991341",
    "stackId": "java-centos",
    "updated": "1538399328400"
  },
  "namespace": "ogaragat-preview",
  "temporary": false,
  "id": "workspace0h2a0unfrqi967tr",
  "status": "RUNNING",
  "runtime": {
    "machines": {
      "dockerimage/tooling7dbwy01p": {
        "attributes": {
          "memoryLimitBytes": "268435456"
        },
        "servers": {
          "che-machine-exec": {
            "url": "ws://routewarirtqd-ogaragat-preview-che.b542.starter-us-east-2a.openshiftapps.com",
            "attributes": {
              "type": "terminal",
              "internal": "false"
            },
            "status": "UNKNOWN"
          }
        },
        "status": "RUNNING"
      },
      "dockerimage/tooling2dmmgn41": {
        "attributes": {},
        "servers": {
          "theia-dev": {
            "url": "http://routejexpj6l8-ogaragat-preview-che.b542.starter-us-east-2a.openshiftapps.com",
            "attributes": {
              "type": "ide-dev",
              "internal": "false"
            },
            "status": "UNKNOWN"
          },
          "theia": {
            "url": "http://routezrve0hk4-ogaragat-preview-che.b542.starter-us-east-2a.openshiftapps.com",
            "attributes": {
              "cookiesAuthEnabled": "true",
              "internal": "false",
              "secure": "true",
              "type": "ide"
            },
            "status": "RUNNING"
          }
        },
        "status": "RUNNING"
      },
      "dev-machine": {
        "attributes": {
          "memoryLimitBytes": "2147483648",
          "memoryRequestBytes": "2147483648"
        },
        "servers": {},
        "status": "RUNNING"
      }
    },
    "warnings": [],
    "activeEnv": "default",
    "machineToken": "",
    "links": []
  },
  "config": {
    "defaultEnv": "default",
    "environments": {
      "default": {
        "machines": {
          "dev-machine": {
            "attributes": {
              "memoryLimitBytes": "2147483648"
            },
            "servers": {},
            "volumes": {},
            "installers": [],
            "env": {
              "CHE_MACHINE_NAME": "dev-machine"
            }
          }
        },
        "recipe": {
          "type": "dockerimage",
          "content": "registry.devshift.net/che/centos_jdk8"
        }
      }
    },
    "projects": [],
    "name": "wksp-7svy",
    "attributes": {
      "editor": "org.eclipse.che.editor.theia:1.0.0",
      "plugins": "che-machine-exec-plugin:0.0.1,che-dummy-plugin:0.0.1"
    },
    "commands": [
      {
        "commandLine": "mvn clean install -f ${current.project.path}",
        "name": "build",
        "attributes": {
          "goal": "Build",
          "previewUrl": ""
        },
        "type": "mvn"
      }
    ],
    "links": []
  }
}
```
<details>
And here is an error I see in the browser console:
<details>

```
Uncaught (in promise) Error: machine with name dockerimage/tooling7dbwy01p was not found. For workspace che.workspace_id
    at Proxy.<anonymous> (proxy-factory.ts:230)
    at n.<anonymous> (remote-terminal-widget.ts:267)
    at terminal-quick-open.ts:84
    at Object.next (terminal-quick-open.ts:84)
    at terminal-quick-open.ts:84
    at new Promise (<anonymous>)
    at a (terminal-quick-open.ts:84)
    at n.createTerminal (remote-terminal-widget.ts:254)
    at n.<anonymous> (remote-terminal-widget.ts:245)
    at terminal-quick-open.ts:84
t @ messages.js:46
(anonymous) @ main.js:430
(anonymous) @ main.js:258
(anonymous) @ main.js:242
(anonymous) @ setImmediate.js:40
u @ setImmediate.js:69
n @ setImmediate.js:109
Promise.then (async)
c @ terminal-quick-open.ts:84
a @ terminal-quick-open.ts:84
Promise.then (async)
c @ terminal-quick-open.ts:84
a @ terminal-quick-open.ts:84
Promise.then (async)
c @ terminal-quick-open.ts:84
(anonymous) @ terminal-quick-open.ts:84
a @ terminal-quick-open.ts:84
n.start @ remote-terminal-widget.ts:236
n.restoreState @ remote-terminal-widget.ts:152
(anonymous) @ shell-layout-restorer.ts:192
Promise.then (async)
e.convertToWidget @ shell-layout-restorer.ts:189
a @ shell-layout-restorer.ts:158
(anonymous) @ shell-layout-restorer.ts:157
e.inflate @ shell-layout-restorer.ts:153
(anonymous) @ shell-layout-restorer.ts:97
(anonymous) @ side-panel-handler.ts:616
(anonymous) @ side-panel-handler.ts:616
a @ side-panel-handler.ts:616
Promise.then (async)
c @ side-panel-handler.ts:616
(anonymous) @ side-panel-handler.ts:616
a @ side-panel-handler.ts:616
e.restoreLayout @ shell-layout-restorer.ts:92
(anonymous) @ frontend-application.ts:206
(anonymous) @ common-frontend-contribution.ts:166
(anonymous) @ common-frontend-contribution.ts:166
(anonymous) @ common-frontend-contribution.ts:166
a @ common-frontend-contribution.ts:166
e.restoreLayout @ frontend-application.ts:204
(anonymous) @ frontend-application.ts:194
(anonymous) @ common-frontend-contribution.ts:166
(anonymous) @ common-frontend-contribution.ts:166
(anonymous) @ common-frontend-contribution.ts:166
a @ common-frontend-contribution.ts:166
e.initializeLayout @ frontend-application.ts:193
(anonymous) @ frontend-application.ts:109
(anonymous) @ common-frontend-contribution.ts:166
(anonymous) @ common-frontend-contribution.ts:166
a @ common-frontend-contribution.ts:166
Promise.then (async)
c @ common-frontend-contribution.ts:166
a @ common-frontend-contribution.ts:166
Promise.then (async)
c @ common-frontend-contribution.ts:166
a @ common-frontend-contribution.ts:166
Promise.then (async)
c @ common-frontend-contribution.ts:166
(anonymous) @ common-frontend-contribution.ts:166
a @ common-frontend-contribution.ts:166
e.start @ frontend-application.ts:100
(anonymous) @ index.js:30
Promise.then (async)
(anonymous) @ index.js:69
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
```
</details>

**Comment by AndrienkoAleksandr** [comment]
@garagatyi Could you provide criteria how to find sidecar? For simple 'machine', che-machine-exec do search by container label(workspace id ) and environment variable CHE_MACHINE_NAME(it would be nice if was machineName container label too).

**Comment by sleshchenko** [comment]
@AndrienkoAleksandr terminal doesn't work in a sidecar container, browser console has the following error
```
Error: machine with name ws/toolingzvn7q2s5 was not found. For workspace che.workspace_id
```
1. First note, looks like `che.workspace_id` is not right one that should be written there.
2. Here is an how Che Server evaluate machine name by Pod and Container name https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Names.java#L47.

> (it would be nice to have machineName container label too).

Sounds reasonable. I will try to handle that on Che Server side and provision `CHE_MACHINE_NAME` environment variable into sidecars containers.

**Comment by sleshchenko** [comment]
I've just created a PR when `CHE_MACHINE_NAME` will be provisioned in all machines including sidecars https://github.com/eclipse/che/pull/11432. I tested `exec`/`terminal` sidecar works just fine with these changes (I tested on local OCP with MultiUser Che where oauth provider is configured)

**Pull request closed without merging**
