### PR TITLE
WIP Update to 7.0.0-beta-3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by fabric8cd**
Tracking changes for fixing compatibility with upstream 7.0.0-beta-3.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/145/console

**Comment by fabric8cd** [comment]
Periodic compatibility check failed. See more details here: https://ci.centos.org/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/146/console

**Comment by ibuziuk** [comment]
```
[INFO] Fabric8 IDE :: Assemblies :: Workspace Agent Server  SUCCESS [ 11.789 s]
[INFO] Fabric8 IDE :: Assemblies :: IDE ................... SUCCESS [  7.075 s]
[INFO] Fabric8 IDE :: Assemblies :: Workspace Master ...... SUCCESS [ 22.756 s]
[INFO] Fabric8 IDE :: Docs ................................ SUCCESS [  0.871 s]
[INFO] Fabric8 IDE :: Assemblies :: Dashboard ............. FAILURE [01:56 min]
[INFO] Fabric8 IDE :: Assemblies :: Main/Tomcat ........... SKIPPED
[INFO] functional-tests ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:53 min
[INFO] Finished at: 2019-03-26T11:31:39+00:00
[INFO] Final Memory: 354M/3125M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-image) on project fabric8-ide-dashboard-war: An Ant BuildException has occured: exec returned: 100
[ERROR] around Ant part ...<exec failonerror="true" dir="/root/payload/assembly/fabric8-ide-dashboard-war" executable="docker">... @ 4:103 in /root/payload/assembly/fabric8-ide-dashboard-war/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fabric8-ide-dashboard-war
Error building che/rh-che with dashboard
Build Failed!
Connection to 172.19.3.109 closed.
```

looks like failure related to https://github.com/redhat-developer/rh-che/issues/1325

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
closed in favour of https://github.com/redhat-developer/rh-che/pull/1333

**Pull request closed without merging**
