### PR TITLE
Revert "Skip functional test in CI because they are broken"

### PR DESCRIPTION
**Pull request by mlabuda**
Reverts redhat-developer/rh-che#171, tests now should run successfuly

### CODE REVIEW

**Comment by l0rd** [comment]
Let's merge that when che-starter is updated in prodution (c.f. https://github.com/openshiftio/saas/pull/256)

**Comment by ibuziuk** [comment]
@l0rd @mlabuda che-starter has been updated on prod, I think we are good to merge

**Comment by l0rd** [comment]
@mlabuda another thing I would like to make sure before merging this PR is that, if the functional tests fail, we (the Che team) need to be able to access the following logs:

- openshift events
- che-server
- wsagent
- bayesian

Not having access to those logs would make almost impossible to understand what is wrong and  address the failure.

**Comment by ibuziuk** [comment]
@rhopp @Katka92 any updates on this issue ? Is it planned to include verification [1] step before pushing images ?

[1] https://github.com/redhat-developer/rh-che/blob/master/.ci/cico_deploy.sh#L32

**Comment by rhopp** [comment]
3 of last ~30 runs failed [1]. Every one of them with different error/failure. We need to investigate those before we can include the verification step before pushing images.

[1] - https://ci.centos.org/view/Devtools/job/devtools-che-functional-tests-periodical/

**Comment by ibuziuk** [comment]
@rhopp thanks for clarifications. Please, let us know if some action is required from dev side. It would be really great to enable verification step in the short run

**Comment by rhopp** [comment]
I've created issue here: https://github.com/redhat-developer/che-functional-tests/issues/139
Closing this PR as I will be providing another PR.

**Pull request closed without merging**
