### PR TITLE
Remove Subversion support from the RH distribution

### PR DESCRIPTION
**Pull request by davidfestal**
Fix for https://issues.jboss.org/browse/CHE-245

Signed-off-by: David Festal <dfestal@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
To me, we should make upstream Che subversion plugin as easy to remove as removing a plugin. Upstream Che is a product, but it is overall a platform.

**Comment by l0rd** [comment]
@davidfestal how hard you think it would be make svn a real plugin in Che upstream? Something we could just remove in our distribution, without the need of a fake plugin.

@sunix I agree with you but we must take into account how urgent it is to remove svn in osio

**Comment by sunix** [comment]
@l0rd yes agree, we should create a task for this and plan it

**Comment by davidfestal** [comment]
@l0rd well, The `SubversionCredentialsDialog` interface is injected into the standard project wizard (through constructor), in case Subversion is used. Adding a default `NoSvnSubversionCredentialsDialog` simply allows Google Gin no to fail. I assume that moving  this class (without binding it) into the upstream Che (in the SVN core API module) would avoid the need to provide it in a fake plugin. However the Gin binding of the `SubversionCredentialsDialog` to the `NoSvnSubversionCredentialsDialog` would still be needed in the RH assembly code.

Alternatively, removing the use of this interface from the project wizard code in the upstream che would certainly require a broader refactoring.

@sunix @l0rd I also think that should be done as part of a new issue. And when working on it, we might be able to remove the fake nosvn plugin from the RH assembly.

**Comment by davidfestal** [comment]
@l0rd @gorkem Is it OK to merge this then ?

**Comment by gorkem** [comment]
@davidfestal can you raise this up on upstream.

**Comment by davidfestal** [comment]
> @davidfestal can you raise this up on upstream.

https://github.com/eclipse/che/issues/5271

**Comment by davidfestal** [comment]
@gorkem @l0rd are you OK to merge this ?

**Comment by l0rd** [comment]
Ok for me

**Comment by davidfestal** [comment]
@gorkem is it OK for you too ?

**Comment by gorkem** [comment]
@davidfestal yes, please go ahead.

**Comment by sunix** [comment]
https://github.com/eclipse/che/pull/4490

**Pull request merged**
