### PR TITLE
rh-che #881: Updating rhche to 6.11.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Updating rhche to 6.11.0 upstream version

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/881

### How have you tested this PR?
Not tested

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by garagatyi** [comment]
@ibuziuk this PR would restart Che master. We also need to add che-plugin-registry env var (+config map entry), so doesn't it make sense to do add them here?

**Comment by ibuziuk** [comment]
@garagatyi I was thinking that we were planning to do it in a separate PR, since this would require creating HK issue with request for adding new entries to `rhche` cm by SD team. Just want to make 6.11.0 available for testing ASAP wdyt ?

**Comment by garagatyi** [comment]
@ibuziuk OK, I just think that it would be better to update prod 1 time instead of 2

**Comment by ibuziuk** [comment]
@garagatyi well, we could update prod once, even though we should not be afraid of doing it twice ;-) for now just want to have it on prod-preview ;-)

**Pull request merged**
