### PR TITLE
Skipping scala devfile

### PR DESCRIPTION
**Pull request by ScrewTSW**
Signed-off-by: Tibor Dancs <tdancs@redhat.com>

### What does this PR do?
Disables scala devfile test in pre-release suite

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18662

### How have you tested this PR?
manually

### CODE REVIEW

**Review by Katka92 — APPROVED** [review]

**Review by ibuziuk — CHANGES_REQUESTED** [review]
please, change the base to `upstream-check-7.26.0-SNAPSHOT`

**Comment by ScrewTSW** [comment]
test

**Comment by ScrewTSW** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
