### PR TITLE
Update to 7.25.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.25.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by Katka92** [comment]
https://rhche-prcheck-2039.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
https://rhche-prcheck-2039.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2039.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
Pre-release tests are failing on know issues Scala, Quarkus and .NET tests. No new bug found by pre-release tests.

**Comment by ibuziuk** [comment]
> Pre-release tests are failing on know issues Scala, Quarkus and .NET tests. No new bug found by pre-release tests.

@Katka92 do we have an issue for .NET?

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2039.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
```
142 passing (49m)
  2 pending
  4 failing
```
- https://github.com/eclipse/che/issues/18663 (Quarkus)
- https://github.com/eclipse/che/issues/18662 (Scala)

@Katka92 @ScrewTSW please create issues for 2 .NET failures during pre-release

  1) Test .NET Core
       Language server validation
         Suggestion invoking:
     TimeoutError: Wait timed out after 31645ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Editor.waitSuggestionWithoutResettingCursor (/tmp/e2e/dist/pageobjects/ide/Editor.js:390:45)
      at Editor.waitSuggestion (/tmp/e2e/dist/pageobjects/ide/Editor.js:58:20)
      at Context.test (/tmp/e2e/dist/testsLibrary/LsTests.js:48:22)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) Test .NET Core
       Language server validation
         Autocomplete:
     TimeoutError: Wait timed out after 31012ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Editor.waitSuggestionWithScrolling (/tmp/e2e/dist/pageobjects/ide/Editor.js:92:45)
      at Context.test (/tmp/e2e/dist/testsLibrary/LsTests.js:57:22)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Review by ibuziuk — APPROVED** [review]

**Comment by Katka92** [comment]
@ibuziuk issue created https://github.com/eclipse/che/issues/18891

**Review by Katka92 — APPROVED** [review]

**Pull request merged**
