### PR TITLE
Updating rh-che to the Che 7 GA upstream version on prod-preview

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the Che 7 GA upstream version

### What issues does this PR fix or reference?
First part of the https://github.com/redhat-developer/rh-che/issues/1490

### How have you tested this PR?
PR CI check

### CODE REVIEW

**Comment by ibuziuk** [comment]
> + echo 'Che functional tests failed. Error code:125'

@Katka92 could you please take a look?

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
Functional tests are failing due to upstream PR https://github.com/eclipse/che/pull/14062, which updated files related to login.

**Comment by amisevsk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk  Test are failing because of https://github.com/redhat-developer/rh-che/issues/1565

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
