### PR TITLE
Add instructions to build rh-che docker image

### PR DESCRIPTION
**Pull request by l0rd**
In README.md we currently have only instructions to build che maven assembly. Nothing is said about how to deploy the assembly to OpenShift. This PR goal is to fill this gap.

### CODE REVIEW

**Comment by l0rd** [comment]
@davidfestal not sure if this doc will be needed after we merge #78. That depends on how much you are going to cleanup README.md. In any case let's merge #78 and then discuss that.

**Comment by davidfestal** [comment]
I'm mostly changing the second part of the Readme. So it will be complementary IMO

**Comment by humaton** [comment]
If this was part of the README week ago we would save some time. Current build instructions are not complete.

**Comment by l0rd** [comment]
This PR can be closed because it has been outdated by other commits

**Pull request closed without merging**
