### PR TITLE
rh-che-212 : Store logs of the che-server on a persistent volume

### PR DESCRIPTION
**Pull request by benoitf**
it will be /data/logs/ folder (/data being used as persistent volume)

Change-Id: I5f5d32ed6f4090ba3a6896a6d6a0203ea01a6f79
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
Needs to be sync with https://github.com/fabric8io/fabric8-online/pull/327

**Comment by benoitf** [comment]
@l0rd do you have a list of these other PRs to be merged ?

**Comment by l0rd** [comment]
@benoitf I mean https://github.com/fabric8io/fabric8-online/pull/327 need to be merged before

**Comment by benoitf** [comment]
@l0rd OK I was thinking it was the opposite, this one first.

**Comment by l0rd** [comment]
@benoitf I think you are right :-P By the way we are ready to merge now.

**Pull request merged**
