### PR TITLE
Changes to configmaps in create-all for memory constraints, java opts

### PR DESCRIPTION
**Pull request by l0rd**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@l0rd I got:

```
# Create configmaps...
error: invalid literal source che-server-java-opts=-XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1000m, expected key=value

```

**Comment by l0rd** [comment]
@ibuziuk I cannot reproduce it locally. Can you try to execute:

```shell
oc create configmap justatest \
   --from-literal=test="-aa:+bb cc"
```

and if it fails can you try removing some chars to see which one is disturbing?

**Comment by ibuziuk** [comment]
@l0rd `justatest` works fine (oc v1.2.2)

**Comment by ibuziuk** [comment]
@l0rd this one fails though :/

```
oc create configmap justatest \  
--from-literal=test="-aa:+bb cc=dd"
```

**Comment by ibuziuk** [comment]
@amisevsk could you reproduce the same error (maybe it is linux specific) ?

**Comment by amisevsk** [comment]
I will give it a shot in a little bit.

**Comment by snjeza** [comment]
@l0rd @ibuziuk @amisevsk 
It works on Fedora 24 with oc 1.4.1

```
oc get configmap che -o yaml
apiVersion: v1
data:
  che-oauth-github-forceactivation: "true"
  che-server-evaluation-strategy: single-port
  che-server-java-opts: -XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40
    -XX:MaxRAM=1000m
  che-workspaces-java-opts: -XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40
    -XX:MaxRAM=1500m
  docker-connector: openshift
  enable-workspaces-autostart: "false"
  hostname-http: che.192.168.42.132.nip.io
  local-conf-dir: /etc/conf
  log-level: DEBUG
  openshift-serviceaccountname: che
  port: "8080"
  remote-debugging-enabled: "true"
  workspace-storage: /home/user/che/workspaces
  workspace-storage-create-folders: "false"
  workspaces-memory-limit: 1500Mi
  workspaces-memory-request: 500Mi
kind: ConfigMap
metadata:
  creationTimestamp: 2017-03-31T16:39:50Z
  name: che
  namespace: eclipse-che
  resourceVersion: "19531"
  selfLink: /api/v1/namespaces/eclipse-che/configmaps/che
  uid: a923504e-1630-11e7-ac49-1e66bc645454
```

**Comment by amisevsk** [comment]
@l0rd @ibuziuk The changes work for me as well.

I'm running 
```
> oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
with Fedora 25.

**Comment by l0rd** [comment]
I'm running

```bash
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth
```

So it may be oc version

**Comment by ibuziuk** [comment]
updating to 1.4.1 did the trick, however even with this fix I got Insufficient memory error on workspace creation

**Comment by snjeza** [comment]
@ibuziuk 

If you are using minishift, try the following:

```
minishift config set memory 4096
```

**Comment by ibuziuk** [comment]
@snjeza thanks - setting memory helped! 
+ 1 to apply

**Comment by l0rd** [comment]
@ibuziuk your issue should be fixed by https://github.com/eclipse/che/pull/4671 too (without the need to increase memory of the VM to 4GB)

**Pull request merged**
