### PR TITLE
Decrease ping success threshold and add ping interval

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
- Add property added in upstream 6.14.2 to control interval for liveness checks on servers
   - Set interval to 500ms as a starting value -- we can increase if it causes problems
- Decrease ping success threshold to 1 (from 2)
   - I'm not able to reproduce route issues from the past on current OpenShift deployments, both for Che 6 and Che 7 workspaces

Together, these changes trim ~5-7 seconds off of workspace start time for Che 7 workspaces.

### What issues does this PR fix or reference?
#1081 

### How have you tested this PR?
On dev cluster, starting workspaces on prod-preview.

### CODE REVIEW

**Comment by amisevsk** [comment]
Housekeeping PR: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2449

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
currently deployment to dev-cluster is failing with the following error:


> 1) Error converting '' (bound at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperty(CheBootstrap.java:450) (via modules: com.google.inject.util.Modules$OverrideModule -> org.eclipse.che.inject.CheBootstrap$CheEnvironmentVariablesConfigurationModule)) to java.lang.Long
> --
>   | using TypeConverter<Long> which matches identicalTo(class java.lang.Long) (bound at [unknown source]).
>   | Reason: java.lang.RuntimeException: For input string: ""
>   | while locating java.lang.Long annotated with @com.google.inject.name.Named(value=che.workspace.server.ping_interval_milliseconds)
>   | for the 6th parameter of org.eclipse.che.api.workspace.server.hc.ServersChecker.<init>(ServersChecker.java:71)
>   | at org.eclipse.che.api.workspace.server.hc.ServersCheckerFactory.create(ServersCheckerFactory.java:1)
>   | at com.google.inject.assistedinject.FactoryProvider2.initialize(FactoryProvider2.java:666)
>   | at com.google.inject.assistedinject.FactoryModuleBuilder$1.configure(FactoryModuleBuilder.java:335) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> com.google.inject.assistedinject.FactoryModuleBuilder$1)
>   |  
>   | 1 error
>   | at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
>   | at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
>   | at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
>   | at com.google.inject.Guice.createInjector(Guice.java:99)
>   | at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
>   | at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
>   | at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
>   | at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
>   | at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
>   | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>   | at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
>   | at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
>   | at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
>   | at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
>   | at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
>   | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>   | at java.lang.Thread.run(Thread.java:748)
>   | Caused by: java.lang.RuntimeException: For input string: ""
> 

@amisevsk looks like there is some problem with env var naming

**Comment by amisevsk** [comment]
@ibuziuk Should be fixed -- dumb typo in yaml: `valuefrom` instead of `valueFrom`.

**Pull request merged**
