### PR TITLE
Update version of vscode plugin broker

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Update version of vscode plugin broker to workaround VS code marketplace rate limit

### What issues does this PR fix or reference?
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/170
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/171

### CODE REVIEW

**Comment by garagatyi** [comment]
@ibuziuk @tdancs @rhopp @Katka92 Do we need to pass CI tests for such an update?

**Comment by ibuziuk** [comment]
@garagatyi yes, IMO. but if it is urgent let's merge it

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
@ibuziuk no, it is not

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
@ibuziuk @tdancs @rhopp @Katka92 PR check keeps failing because of the postresql start failure. Should I continue restarting it?

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
[test]

**Comment by garagatyi** [comment]
@tdancs @rhopp @Katka92 PR check keeps failing because of the postresql start failure. Should I continue restarting it?

**Comment by Katka92** [comment]
Hi @garagatyi there is PR with workaround https://github.com/redhat-developer/rh-che/pull/1275. This PR was failing because of issues with 2a cluster. If it is not crucial I would wait until PR with workaround is merged and rerun it again after that.

**Comment by garagatyi** [comment]
@Katka92 is it known when the above mentioned PR will be merged?

**Comment by Katka92** [comment]
I don't know. @rhopp will take a look on that PR and maybe provide more info about that.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by garagatyi** [comment]
@ibuziuk thanks for handing the CI checks

**Pull request merged**
