### PR TITLE
Updating rh-che to the 6.18.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating rh-che to the 6.18.0 upstream version

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by garagatyi** [comment]
I don't see any useful information in the logs - Postgres deployment just timed out.

**Comment by ibuziuk** [comment]
@Katka92 could you please investigate why there is this error during functional test execution (rh-che build seems to work just fine)

> [FATAL] Non-resolvable parent POM for com.redhat.che:fabric8-ide-parent:1.0.0-SNAPSHOT: Could not transfer artifact org.eclipse.che:che-parent:pom:6.18.0-SNAPSHOT from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/che/che-parent/6.18.0-SNAPSHOT/che-parent-6.18.0-SNAPSHOT.pom.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
still failing with postgres deployment:

```
[91;1mFailed to start postgres: timed out[0m
Custom che deployment failed. Error code:1
```

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW looks like we are having problems with functional tests:

> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   BuildAndRunProjectTest.checkWorkspace » Provision Unable to provision, see the...
> [ERROR]   WorkspaceTest.testCorrectWayOfStarting:46 » Timeout Expected condition failed:...
> [INFO] 
> [ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 1
> [INFO]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@ScrewTSW @rhopp are you aware of any issues with dev cluster ? looks like deployment postgres is currently failing. Could you please follow up on this with SD ?

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
