### PR TITLE
[DO NOT MERGE] Update to 7.15.1

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.15.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io
[pre-release-tests]
Testing prod-preview with version 7.14.1 before the push to prod.

**Comment by Katka92** [comment]
The test failed on obtaining user token. It's a known issue https://github.com/redhat-developer/rh-che/issues/1630

**Comment by Katka92** [comment]
Today, test was not triggered because of https://github.com/redhat-developer/rh-che/issues/1921. Triggering manually.
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk This job is failing on a building rh-che for quite some time. Is that expected?

**Comment by ibuziuk** [comment]
@Katka92 yes, since we need to migrate to java 11 first - https://github.com/redhat-developer/rh-che/pull/1922

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1909.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
Merging of the PR is postponed. @nickboldt lemme know when we are good to go

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1909.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Pull request merged**
