### PR TITLE
che #18168 Updating Hosted Che to the latest 7.20.1 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Updating Hosted Che to the latest 7.20.1 upstream versoin

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18168

### How have you tested this PR?
PR check CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2004.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2004.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2004.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2004.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2004.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
9 failing tests on quarkus, but this is expected

**Review by Katka92 — APPROVED** [review]

**Pull request merged**
