### PR TITLE
Add monitoring for route exposure time and test for route flapping.

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
There were issues with route exposure time and route flapping. These issues can get back so we decided to create automated CI for monitoring route exposure time and for checking route flapping issue. 
One of a side effect of these issues was that project was not imported correctly and this issue was seen again in [1] on 20th April.

[1] https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/508/console

### How have you tested this PR?
manually against cluster 2

### CODE REVIEW

**Comment by ibuziuk** [comment]
@Katka92 could you please clarify against which namespaces and clusters the route exposure will be tested?

**Comment by Katka92** [comment]
@ibuziuk The test run against ``` username ``` namepsace and against all clusters - 2, 2a, 1a and 1b.

**Comment by Katka92** [comment]
As far as namespace ``` <username> ``` will be removed, we decided to switch it to ``` <username>-che ``` namespace.

**Comment by Katka92** [comment]
[test]

**Pull request merged**
