### PR TITLE
Update to 7.21.1

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.21.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

Upstream issue - https://github.com/eclipse/che/issues/18223

### CODE REVIEW

**Comment by Katka92** [comment]
Test failed to create a workspace `Failed to load devfile meta list` and `Failed to load the devfile registry URL`. 
image

[test]

**Comment by Katka92** [comment]
@ibuziuk It seems we have some problem with testing accoung. Last build failed on:
> Failed to pull image "quay.io/openshiftio/rhel-rhchestage-rh-che-automation:****-1999": rpc error: code = Unknown desc = Error reading manifest ****-1999 in quay.io/openshiftio/rhel-rhchestage-rh-che-automation: unauthorized: access to the requested resource is not authorized`

[test]

**Comment by Katka92** [comment]
Now the devfiles were not loaded correctly.
image

[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW looks like maven test keeps failing

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
Test failed on following:
1x could not deploy che `Error: object "prcheck-1999"/"rhche" not registered` [here](https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/2988/console)
1x Code navigation not working
2x failed to run command in the workspace - seems like test glitch.
1x
image
1x 
image

[test]

**Comment by Katka92** [comment]
It seems our test is having problems with `StaleElementReferenceError`. I'll try to fix that today.

**Comment by Katka92** [comment]
@ibuziuk So according to my investigation, we are not using the newest version of `che-theia`. There was a change in upstream - when running a task, the usual flow was 2 dropdowns are opened - in the first we selected the command to run, in the second we selected `Continue without scanning the output`. The second dropdown [1] is not appearing anymore in the upstream nightly tests but is still appearing here. That's why I blame the `che-theia` to be older then expected.
Change was done [here](https://github.com/eclipse/che-theia/pull/889) and fixed [here](https://github.com/eclipse/che/pull/18172).
I tried to take a look at the logs and I found this error (not sure if it is responsible for the issue)
>[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
07:25:50.167 [main] DEBUG com.redhat.che.cdn.CdnSupportService - Running skopeo on image eclipse/che-theia:next
07:25:50.183 [main] DEBUG com.redhat.che.cdn.CdnSupportService - Result of running skopeo on image eclipse/che-theia:next: {"Labels": { "che-plugin.cdn.artifacts": "cdnJsonContent" }}
07:25:50.209 [main] DEBUG com.redhat.che.cdn.CdnSupportService - Running skopeo on image eclipse/che-theia:next
07:25:50.209 [main] DEBUG com.redhat.che.cdn.CdnSupportService - Result of running skopeo on image eclipse/che-theia:next: {"Labels": { "che-plugin.cdn.artifacts": "cdnJsonContent" }}
07:25:50.384 [main] DEBUG com.redhat.che.cdn.CdnSupportService - Running skopeo on image eclipse/che-theia:next
07:25:50.386 [main] WARN com.redhat.che.cdn.CdnSupportService - skopeo failed when trying to retrieve the CDN label of docker image eclipse/che-theia:next - exit code: 1 - error output: skopeo error output
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.591 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0

[1]
image

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
It seems that `Application not available` is appearing every test run at least 2x. The Java SpringBoot is failing on command running too long - the timeouts are set quite high - for command `maven build` the timeout is 6 minutes - and it seems to not be enough for Hosted Che. Other issues need more investigation but seem more like test ones.

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
@ibuziuk Workspaces were not able to start. Go to the [artifacts](http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-pre-release-test/84/e2e_report/report/) and see the `Wait_for_workspace_readiness` screens. Therea re multiple failure types, but mostly `Failed to start websocket`.

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ScrewTSW** [comment]
[pre-release-tests]

**Comment by ScrewTSW** [comment]
[pre-release-tests]

**Comment by ScrewTSW** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1999.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
