### PR TITLE
WIP DO NOT MERGE

### PR DESCRIPTION
**Pull request by rhopp**
### What does this PR do?
I'm just trying some stuff on ci.centos (which we will need for migration from codenvy ci). 
This is the easiest way for me right now to try things there.

If this PR bothers you, feel free to ping me and close this PR ;-)

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by ibuziuk** [comment]
@rhopp do you still need this PR or can we close it?

**Comment by rhopp** [comment]
Closing. Thx for reminding me.

**Pull request closed without merging**
