### PR TITLE
Updating Hosted Che to the 7.19.0 upstream version. Adding GatewayRouterProvisioner to constructor

### PR DESCRIPTION
**Pull request by tomgeorge**
Signed-off-by: Tom George <tg82490@gmail.com>

### What does this PR do?

Fixes the failed PR check build https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/2884/console

### CODE REVIEW

**Comment by tomgeorge** [comment]
[test]

**Comment by tomgeorge** [comment]
[test]

**Comment by tomgeorge** [comment]
[test]

**Review by amisevsk — APPROVED** [review]
LGTM

**Comment by tomgeorge** [comment]
[test]

**Comment by vparfonov** [comment]
[test]

**Comment by ibuziuk** [comment]
@tomgeorge could you please resolve conflicts? Once done I believe we can simply merge it to `upstream-check-7.19.0-SNAPSHOT` and follow up on the test failures in the main PR - https://github.com/redhat-developer/rh-che/pull/1969

**Review by Katka92 — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
