### PR TITLE
[WIP] rh-che #593: move JSON logs encoding to upstream

### LINKED ISSUE #593: Make json logger log tomcat logs
**Issue problem:** 
We have a configuration that wraps application logs as jsons to store them using ELK stack. These logs contain logs of API war other wars but don't contain logs of tomcat itself. It is very critical because in case api war didn't start correctly there are useful logs with stack traces but they are accessible from the inside of the rh-che pod only.
I believe that we need to add logstash encoder jar to tomcat libs and maybe configure tomcat logger too. 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
[WIP] because needs moving to Che 6.4.0. So we can't merge for now. 
Use new approach to configure JSON encoding of logs and remove
the old one.
New approach logs not only war logs but also logs of tomcat.

### What issues does this PR fix or reference?
Fixes #593 
Related to https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1632

### How have you tested this PR?
On dev cluster

### CODE REVIEW

**Comment by garagatyi** [comment]
@mmclanerh thank you!

**Comment by garagatyi** [comment]
@sunix @l0rd @ibuziuk Please, review the PR.

**Comment by ScrewTSW** [comment]
@here please ignore the jenkins job for now, the cico script is not merged yet and will be failing for a while.

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Pull request merged**
