### PR TITLE
Update to 7.22.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.22.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
https://rhche-prcheck-2006.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ScrewTSW** [comment]
https://rhche-prcheck-2006.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
https://rhche-prcheck-2006.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
Found issues in pre-release suit: 
 - build command timeouts - test issue
 - checking terminal fails - not sure what is the issue there, need deeper investigation

**Comment by Katka92** [comment]
https://rhche-prcheck-2006.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2006.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
```
  141 passing (46m)
  2 pending
  5 failing
```

@Katka92 @ScrewTSW do we have issues for the failing tests? are we good to promote to staging

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2006.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
