### PR TITLE
che #18342 Updating Hosted Che to the latest 7.21.2 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Updating Hosted Che to the latest 7.21.2 upstream version

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18342

### How have you tested this PR?
PR check

### CODE REVIEW

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2012.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2012.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2012.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2012.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Review by ScrewTSW — APPROVED** [review]

**Pull request merged**
