### PR TITLE
Update to 7.14.1

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.14.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by Katka92** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

Previous tests failed on JavaMaven glitch, other tests passed. Reruning again.

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
The last tests failed because of `Application not available` during an IDE loading. Rerunning. 
[test]

**Comment by Katka92** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

Reasons for previous fails in pre-release test suites:
**Run 22**
 - Application not available during Python test

**Run 23**
 - Application not available during Python test

**Run 24**
 - Application not available during Go test
 - Workspace restart during JavaMaven workspace startup
 - `maven build` command not succeeded during JavaMaven test

**Comment by Katka92** [comment]
Pre-release test suite report for run 25:
 - Application not available during Go test
 - Workspace restart during JavaMaven workspace startup
 - `maven build` command not succeeded during JavaMaven test
 - Application not available during JavaVertx test

**Comment by ibuziuk** [comment]
@Katka92 this looks strange:
```
Successfully tagged e2e_tests:latest
All mandatory parameters were set. Running Che 7 Theia E2E tests against https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com with user ****.
Trying to find token for rh- che-automation-preview
ACCOUNT_ENV variable is not set, retrieving env from username.
Failed to obtain token for ****! Probably user password is incorrect. 
Running functional tests lasted 209 seconds.
```

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
> @Katka92 this looks strange:
> 
> ```
> Successfully tagged e2e_tests:latest
> All mandatory parameters were set. Running Che 7 Theia E2E tests against https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com with user ****.
> Trying to find token for rh- che-automation-preview
> ACCOUNT_ENV variable is not set, retrieving env from username.
> Failed to obtain token for ****! Probably user password is incorrect. 
> Running functional tests lasted 209 seconds.
> ```

It is a known issue, it is also present in periodic jobs: https://github.com/redhat-developer/rh-che/issues/1630 I don't think it's a test issue.

**Comment by Katka92** [comment]
Test failed due to Application not available. Rerunning tests.
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
Test failed because of Application not available.

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk the previous test failed on:
image
Is that expected?

**Comment by ibuziuk** [comment]
looks like we need to wait for `7.14.1` - `7.14.0` seem to be broken :shrug:

**Comment by Katka92** [comment]
Failed on a same error.

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1894.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Pull request merged**
