### PR TITLE
Updates to tag versions based on current stack images used

### PR DESCRIPTION
**Pull request by kevchu3**
### What does this PR do?
This update to the stacks definition file will properly allow the Workspaces UI interface to display the correct tags and minor version numbers used.

### What issues does this PR fix or reference?
For some stacks, the component minor version numbers are incorrect.

### How have you tested this PR?
Yes, tested each stack image by spinning it up and checking versions.

### CODE REVIEW

**Comment by ibuziuk** [comment]
@kevchu3 thanks for the PR, but in the short run we are going to switch from stacks to devfiles - https://github.com/eclipse/che-devfile-registry

**Comment by ibuziuk** [comment]
@skabashnyuk am I correct that stacks.json has been removed in the latest upstream rc4 release as part of Che 6 legacy code cleanup https://github.com/eclipse/che/pull/13788? Basically, in rc4 "Stacks" tab of UD is based on devfiles, right ?

**Comment by skabashnyuk** [comment]
>@skabashnyuk am I correct that stacks.json has been removed in the latest upstream rc4 release as part of Che 6 legacy code cleanup eclipse/che#13788?

They not.   https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/test/resources/stacks.json planning to do that as part of  https://github.com/eclipse/che/issues/13459

**Comment by ibuziuk** [comment]
@skabashnyuk thanks for the clarification. For some reason, I thought that `stacks.json` was part of `ide` folder that was removed in the latest release. Am I correct that currently neither `stacks.json` nor stacks service are used by UD in rc 4?

**Comment by skabashnyuk** [comment]
Not sure about rc4 it has to be received in git history.

**Comment by ibuziuk** [comment]
Closing since stacks.json were removed as part of the https://github.com/redhat-developer/rh-che/pull/1481

@kevchu3 if you have any suggestion please contribute to https://github.com/eclipse/che-devfile-registry
Devfile info - https://redhat-developer.github.io/devfile/

**Comment by kevchu3** [comment]
> Closing since stacks.json were removed as part of the #1481
> 
> @kevchu3 if you have any suggestion please contribute to https://github.com/eclipse/che-devfile-registry
> Devfile info - https://redhat-developer.github.io/devfile/

That makes sense, and thanks

**Pull request closed without merging**
