### PR TITLE
[DO NOT MERGE] Rolling back to the 7.3.0 upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Rolling back to the 7.3.0 upstream version

### What issues does this PR fix or reference?
Plan B for https://github.com/redhat-developer/rh-che/issues/1705

### How have you tested this PR?
PR check CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
I tested manually and the 7.3.0 on dev cluster seem to work just fine:

image

@Katka92 could you please take a look at the test failure ?

**Comment by Katka92** [comment]
The first test failed because README popped-up and stole a focus. The second test failed because LS was not initialized. I'll rerun tests.

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Pull request closed without merging**
