### PR TITLE
Updating to the latest 7.0.0-beta-5.0 upstream release

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating to the latest 7.0.0-beta-5.0 upstream release

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1418

### How have you tested this PR?
Supposed to be tested by PR check

### CODE REVIEW

**Comment by ibuziuk** [comment]
looks like some changes on CDN end:

>   location: class HttpYamlDownloader
> /root/payload/plugins/fabric8-cdn-support/src/main/java/com/redhat/che/cdn/HttpYamlDownloader.java:52: error: cannot find symbol
>   protected PluginMeta parseYamlResponseStreamAndClose(InputStream inputStream) throws IOException {
>             ^
>   symbol:   class PluginMeta
>   location: class HttpYamlDownloader

@davidfestal any ideas?

**Comment by davidfestal** [comment]
> looks like some changes on CDN end:
> 
> > location: class HttpYamlDownloader
> > /root/payload/plugins/fabric8-cdn-support/src/main/java/com/redhat/che/cdn/HttpYamlDownloader.java:52: error: cannot find symbol
> > protected PluginMeta parseYamlResponseStreamAndClose(InputStream inputStream) throws IOException {
> > ^
> > symbol:   class PluginMeta
> > location: class HttpYamlDownloader
> 
> @davidfestal any ideas?

@amisevsk it seems the `HttpYamlDownloader` has be created quite recently in this commit https://github.com/redhat-developer/rh-che/commit/bb245dbc2732303145fa3e0180bb8c1aae77e3fc#diff-18816845e8cef2e2f0e6d8aad57ad603
Any idea ?

**Comment by amisevsk** [comment]
CDN support in downstream rh-che requires getting the `meta.yaml` for the editor to be served via CDN. Since plugin meta downloading has been moved into the broker it is necessary to move the yaml downloading functionality into the CDN support instead of relying on `PluginMetaRetriever`, which has been removed.

**Comment by amisevsk** [comment]
The actual issue here is that `PluginMeta` has also been removed as it is no longer needed in upstream: https://github.com/eclipse/che/commit/3e6d195f48f1d3c394df2cbf483cc0581acc3a01#diff-e85e3d20ee24d99086c30e5dd5e42ae2

**Comment by ibuziuk** [comment]
closing in favour of https://github.com/redhat-developer/rh-che/pull/1433

**Pull request closed without merging**
