### PR TITLE
Update to upstream 7.4.0

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Update to upstream 7.4.0
- Port changes in 7.4.0 
- Update dashboard (disable devfile editor autosave)

### CODE REVIEW

**Comment by amisevsk** [comment]
Removed WIP status, as I think 7.3.2 is stable on production.

**Comment by ibuziuk** [comment]
@amisevsk it looks like that 7.4.0 is affected by https://github.com/eclipse/che/issues/15006 
I would propose to use this PR for 7.5.0 update (upstream release is planned this week)

**Comment by Katka92** [comment]
[test]

**Comment by amisevsk** [comment]
I have added 5 commits to let us move to 7.5.1:
- https://github.com/redhat-developer/rh-che/pull/1701/commits/6061e232919449fab6b1c6b299959d5d692c6b62 : A basic sync of changed upstream dashboard files. PR https://github.com/eclipse/che/pull/15143 adds the ability to specify a devfile directly, and as a result, the create-workspace page has been updated. This commit moves the ephemeral mode toggle (and setting ephemeral mode = `true` by default) to the new `ready-to-go-stacks` controller.
- https://github.com/redhat-developer/rh-che/pull/1701/commits/c289334557c2a6efdade4329db093be4b2094fce : fixes the dashboard build in general:
    - PR https://github.com/eclipse/che/pull/12911causes any webpack error to cause the build to fail
    - To workaround a typescript issue, PR https://github.com/eclipse/che/pull/15112/files adds `index.d.ts`; however this file does not appear to be included in build artifacts, so this commit adds it to our dashboard directory and updates the build to copy it appropriately
- https://github.com/redhat-developer/rh-che/pull/1701/commits/083102ae74cd1080809200196782848fda832229 : **comments out** `che-ide-fetcher.service.ts. As a result of the above webpack change, a long standing (?) issue is revealed: PR https://github.com/eclipse/che/commit/32515517bf removed `che-ide-fetcher.service.ts` from the repo, and also removed method `getIdeResourcesPath` from CheBranding. This occurred for 7.3.0 as far as I can tell, but since webpack errors didn't fail the build previously, our class calling the nonexistent method did not seem to raise errors.
    - The specifically failing line is [here](https://github.com/redhat-developer/rh-che/blob/ee80af3cae322e3db74cee5ec7a2effb3d8f2446/assembly/fabric8-ide-dashboard-war/src/components/ide-fetcher/che-ide-fetcher.service.ts#L149), though it's not clear how to use this class given that it's removed upstream.
- https://github.com/redhat-developer/rh-che/pull/1701/commits/44730030fa472aa26fdde20b979b5ae38d48b4e4 : the usual "update our classes to accomodate changes to upstream APIs" -- mostly just changing constructor signatures
- https://github.com/redhat-developer/rh-che/pull/1701/commits/7b9cb76bff887a07e1e9f6d9b9c6c4dff8d85b12 : remove the `DisableAuthenticationInterceptor` from rh-che, as PR https://github.com/eclipse/che/pull/15000 removes AbstractKeycloakFilter. I'm not sure this is the correct thing to do here, but as far as I can tell, the interceptor is no longer necessary.

The changes I think are important to double check are:
1. Does removing `che-ide-fetcher.service.ts` from the repo cause problems, and what are our options in bringing it back?
2. Ensure there are no issues around `DisableAuthenticationInterceptor`, as the upstream PR is quite complex so it's hard to say for sure what additional changes may be necessary.

**Comment by amisevsk** [comment]
Looks like there are some issues with commit https://github.com/redhat-developer/rh-che/commit/7b9cb76bff887a07e1e9f6d9b9c6c4dff8d85b12, as I'm seeing a "Authorization token is missing" error when trying to access the dashboard.

**Comment by ibuziuk** [comment]
@amisevsk I have provided a PR based on your commits for 7.5.1 update - https://github.com/redhat-developer/rh-che/pull/1722 (PR check seem to be passing). Are you ok to close this one in favour of https://github.com/redhat-developer/rh-che/pull/1722 ?

**Comment by amisevsk** [comment]
Closing in favor of #1722, thanks for fixing @ibuziuk

**Pull request closed without merging**
