### PR TITLE
Separate PR deployments

### PR DESCRIPTION
**Pull request by ScrewTSW**
### What does this PR do?
Creates a separate namespace for every open PR, leaving the servers deployed for testing until PR is closed. Then the namespaces will be deleted. This should allow concurrency and faster, more responsive PR Check.

- [X] Separate deployments into specific namespace
- [X] Run tests against specific deployment
- [X] Investigate possibilities of cleanup job
- [x] Implement cleanup job

### What issues does this PR fix or reference?
edhat-developer/che-functional-tests/issues/357

### How have you tested this PR?
pr-check testing.

### CODE REVIEW

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by ScrewTSW** [comment]
Build and deployment fixed, moving onto running tests against the deployment

**Comment by garagatyi** [comment]
Cool!!!

**Pull request merged**
