### PR TITLE
rh-che #1409 Updating 'CHE_FABRIC8_USER__SERVICE_ENDPOINT' due to the fact that `/api/user/services` was moved from WIT to Auth service

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Updating 'CHE_FABRIC8_USER__SERVICE_ENDPOINT' due to the fact that `/api/user/services` was moved from WIT to Auth service

### What issues does this PR fix or reference?
#1409

### How have you tested this PR?
PR check / dev-cluster

### CODE REVIEW

**Comment by ibuziuk** [comment]
@davidfestal good point, btw I think we should remove `CHE_FABRIC8_USER__SERVICE_ENDPOINT` completely and fall back on `CHE_FABRIC8_AUTH_ENDPOINT` with `/api/user/services` path

**Comment by ibuziuk** [comment]
@davidfestal could you please point where e2e should be changed?

**Comment by ibuziuk** [comment]
[test]

**Comment by davidfestal** [comment]
@ibuziuk https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-end2end-flow/src/main/resources/end2end/files/RhCheKeycloak.js#L490

**Comment by ibuziuk** [comment]
@alexeykazakov @sbryzak looks like the brand-new new endpoint does not work as expected:

image

```
Caused by: java.io.IOException: Failed access: https://auth.prod-preview.openshift.io/api/user/services?token , method: GET, response code: 500, message: {"errors":[{"code":"unknown_error","detail":"panic: runtime error: invalid memory address or nil pointer dereference\npanic(0xbe46c0, 0x140d5c0)\n\t/usr/lib/golang/src/runtime/panic.go:513 +0x1b9\ngithub.com/fabric8-services/fabric8-auth/controller.(*UserServiceController).Show(0xc000376da0, 0xc0003c9e80, 0xc000811a00, 0xc000266ea0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/controller/user_service.go:25 +0x2e\ngithub.com/fabric8-services/fabric8-auth/app.MountUserServiceController.func1(0xe10240, 0xc000138270, 0xe0de40, 0xc000655800, 0xc000811a00, 0x0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/app/controllers.go:57 +0xdd\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware/security/jwt.New.func1.1(0xe10240, 0xc00009df50, 0xe0de40, 0xc000655800, 0xc000811a00, 0xe10240, 0xc00009df50)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware/security/jwt/jwt.go:123 +0x4c3\ngithub.com/fabric8-services/fabric8-auth/app.handleSecurity.func1(0xe10240, 0xc00009df50, 0xe0de40, 0xc000655800, 0xc000811a00, 0xc26cc0, 0xc000655800)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/app/security.go:49 +0x177\ngithub.com/fabric8-services/fabric8-auth/app.handleUserServiceOrigin.func1(0xe10240, 0xc00009dad0, 0xe0de40, 0xc000655800, 0xc000811a00, 0x0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/app/controllers.go:73 +0x4e4\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa.(*Controller).MuxHandler.func1.1(0xe10240, 0xc00009dad0, 0xe0de40, 0xc000655800, 0xc000811a00, 0x0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/service.go:270 +0x9b\ngithub.com/fabric8-services/fabric8-auth/log.LogRequest.func1.1(0xe10240, 0xc00009dad0, 0xe0de40, 0xc000655800, 0xc000811a00, 0xc00009d9b0, 0xe10240)\
--
  | n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/log/log_request.go:90 +0xd0a\ngithub.com/fabric8-services/fabric8-auth/authorization/token/manager.InjectTokenManager.func1.1(0xe10240, 0xc00009d950, 0xe0de40, 0xc000655800, 0xc000811a00, 0x0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/authorization/token/manager/token_manager.go:171 +0x98\ngithub.com/fabric8-services/fabric8-auth/goamiddleware.handler.func1(0xe10240, 0xc0004a2b70, 0xe0de40, 0xc000655800, 0xc000811a00, 0xc000740bb0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/goamiddleware/jwt_token_context.go:63 +0x28f\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware.Recover.func1.1(0xe10240, 0xc0004a2b70, 0xe0de40, 0xc000655800, 0xc000811a00, 0x0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware/recover.go:37 +0x93\ngithub.com/fabric8-services/fabric8-auth/jsonapi.ErrorHandler.func1.1(0xe10240, 0xc0004a2b70, 0xe0de40, 0xc000655800, 0xc000811a00, 0xc0006ae7a0, 0x14)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/jsonapi/error_handler.go:37 +0xb4\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware/gzip.Middleware.func2.1(0xe10240, 0xc0004a2b70, 0xe0de40, 0xc000655800, 0xc000811a00, 0x0, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware/gzip/middleware.go:69 +0xec\ngithub.com/fabric8-services/fabric8-auth/log.LogRequest.func1.1(0xe10240, 0xc0004a2b70, 0xe0de40, 0xc000655800, 0xc000811a00, 0xc00031c070, 0xe10240)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/log/log_request.go:90 +0xd0a\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware.RequestIDWithHeaderAndLengthLimit.func1.1(0xe10240, 0xc0004a29c0, 0xe0de40, 0xc000655800, 0xc000811a00, 0xc0004a2930, 0xe10240)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/middleware/request_id.go:63 +0x144\ngithub.com/fabr
  | ic8-services/fabric8-auth/vendor/github.com/goadesign/goa.(*Controller).MuxHandler.func1(0xe0f7c0, 0xc000302d20, 0xc000811a00, 0xc0004a2930)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/service.go:303 +0x327\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa.(*mux).Handle.func1(0xe0f7c0, 0xc000302d20, 0xc000811a00, 0x0)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/mux.go:59 +0x1c4\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc000189900, 0xe0f7c0, 0xc000302d20, 0xc000811a00)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/dimfeld/httptreemux/router.go:200 +0xe5\ngithub.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa.(*mux).ServeHTTP(0xc0003a3d50, 0xe0f7c0, 0xc000302d20, 0xc000811a00)\n\t/tmp/go/src/github.com/fabric8-services/fabric8-auth/vendor/github.com/goadesign/goa/mux.go:85 +0x4c\nnet/http.(*ServeMux).ServeHTTP(0x14210c0, 0xe0f7c0, 0xc000302d20, 0xc000811a00)\n\t/usr/lib/golang/src/net/http/server.go:2361 +0x127\nnet/http.serverHandler.ServeHTTP(0xc0002d2340, 0xe0f7c0, 0xc000302d20, 0xc000811a00)\n\t/usr/lib/golang/src/net/http/server.go:2741 +0xab\nnet/http.(*conn).serve(0xc0002bf860, 0xe10180, 0xc000655740)\n\t/usr/lib/golang/src/net/http/server.go:1847 +0x646\ncreated by net/http.(*Server).Serve\n\t/usr/lib/golang/src/net/http/server.go:2851 +0x2f5\n","status":"500","title":"Unknown error"}]}
  |  
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:285)
  | at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
  | at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.getResponseBody(TenantDataCacheLoader.java:91)
  | at com.redhat.che.multitenant.tenantdata.TenantDataCacheLoader.load(TenantDataCacheLoader.java:52)
  | ... 98 common frames omitted
```
ideas ?

**Comment by sbryzak** [comment]
@ibuziuk I'm working on this right now, hopefully it's a minor issue.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@davidfestal PR is ready for review. Do you happen to know if it is possible to test properly e2e registration flow against prod-preview (AFAIK it still require manual approval cc: @sbose78 @alexeykazakov) ?

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
hmm.. looks like `api` prefix is added twice for some reason:

> Access to XMLHttpRequest at 'https://auth.prod-preview.openshift.io/api/api/users?filter%5Busername%5D=osio-ci-ee3-preview' from origin 'http://rhche-prcheck-1443.devtools-dev.ext.devshift.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ibuziuk** [comment]
tested manually against che 7 and che 6 and the workspace startup seems to work just fine

[test]

**Comment by alexeykazakov** [comment]
> Do you happen to know if it is possible to test properly e2e registration flow against prod-preview (AFAIK it still require manual approval)

Prod-preview still requires manual approval.

**Comment by ibuziuk** [comment]
@alexeykazakov ok, than will need your help before promoting this change to prod

**Comment by ibuziuk** [comment]
@davidfestal tested e2e flow against https://rhche-dfestal-preview-che.devtools-dev.ext.devshift.net and all seems works just fine. Would appreciate if you could review and potentially take a look at e2e flow on https://rhche-dfestal-preview-che.devtools-dev.ext.devshift.net

**Pull request merged**
