### PR TITLE
che-15261: Update with upstream che

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Add missing files to `assembly-ide-war`

### What issues does this PR fix or reference?
https://github.com/eclipse/che/pull/16488

### How have you tested this PR?
Built the project and checked that the `fabric8-ide-assembly-ide-war-1.0.0-SNAPSHOT.war` includes missing files

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
@vinokurig Ah, I re-run the tests but I didn't realize that the branch will need a rebase. Could you please rebase your branch? Thank you

**Comment by vinokurig** [comment]
[test]

**Comment by vinokurig** [comment]
@Katka92 done

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
Thanks @vinokurig !

**Pull request merged**
