### PR TITLE
Update to 7.8.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.8.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW why the PR check is not triggered?

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk PR check was not triggered because the compatibility test reached timeout. Currently, the timeout is set to 20 minutes which is quite low. I'll create PR to increase this timeout and set an error message if job timeouts again.

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
Tests reached timeout again, the PR with a fix was merged, we'll see if it will help.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
Compatibility test failed on installing dependencies - the reason is dirty node, I've raised that again on ci-users mailing list.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Test failed because of tests - there is some problem so tests were not executed. This requires a fix from our side. I'll take a look at that today/tomorrow.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ScrewTSW** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
