### PR TITLE
che #18770 Updating Hosted Che to the latest '7.24.1' upstream version

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Updating Hosted Che to the latest '7.24.1' upstream version

### What issues does this PR fix or reference?
Related issue - https://github.com/eclipse/che/issues/18770

### How have you tested this PR?
PR check CI

### CODE REVIEW

**Comment by ibuziuk** [comment]
@Katka92 could you please take a look at the failure:

```Failed to pull image "quay.io/openshiftio/rhel-rhchestage-rh-che-automation:rhcheautomation-2032": rpc error: code = Unknown desc = Error reading manifest rhcheautomation-2032 in quay.io/openshiftio/rhel-rhchestage-rh-che-automation: unauthorized: access to the requested resource is not authorized```

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
The same failure again even though it looks like image built:

````
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Created / tagged the following Eclipse Che images:
!      quay.io/rhchestage/rh-che-automation:nightly-**** quay.io/rhchestage/rh-che-automation:****-2032
! in the local Docker environment
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
After build:
REPOSITORY                                              TAG                       IMAGE ID       CREATED          SIZE
quay.io/openshiftio/rhel-rhchestage-rh-che-automation   nightly-****   5623779878a4   17 seconds ago   679MB
quay.io/openshiftio/rhel-rhchestage-rh-che-automation   ****-2032      5623779878a4   17 seconds ago   679MB
```

![image](https://user-images.githubusercontent.com/1461122/104307393-77372c00-54cf-11eb-9d67-970ab2be8c4c.png)

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2032.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Review by Katka92 — APPROVED** [review]

**Comment by ibuziuk** [comment]
pre-release failed with Killed by signal 15 / timeout, going to be retested as part of a promotion to production

**Pull request merged**
