### PR TITLE
Updated verification of Che, added functional tests

### PR DESCRIPTION
**Pull request by mlabuda**
This PR should be merged once https://github.com/almighty/almighty-jobs/pull/195 is merged.

### CODE REVIEW

**Comment by mlabuda** [comment]
@l0rd could you review, please?

**Comment by l0rd** [comment]
@mlabuda can you please point me to a jenkins job that run these tests successfully?

**Comment by mlabuda** [comment]
@l0rd  https://ci.centos.org/view/Devtools/job/devtools-che-test-end-to-end/ I am making few changes because tests evolved from end to end to functional. I did few renames and I have pending PR in almighty jobs repo to rename test as well.

**Comment by l0rd** [comment]
Ok thanks I will try to have a look at it later today

Il 23 giu 2017 9:03 AM, "Marián Labuda" <notifications@github.com> ha
scritto:

**Comment by mlabuda** [comment]
Ok, this is the new CI job https://ci.centos.org/view/Devtools/job/devtools-che-functional-tests/ 
I will have to tear down the old one, to avoid "race condition". Waiting for guys with admin rights on ci.centos.org to do it.

**Comment by davidfestal** [comment]
So @mlabuda do you confirm it's OK to go to master ?

**Comment by mlabuda** [comment]
yeah, +1

**Pull request merged**
