### PR TITLE
WIP Adding support of `none` pvc strategy in order to start testing ephemeral workspaces

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Adding support of `none`  pvc strategy in order to start testing ephemeral workspaces

### What issues does this PR fix or reference?
Required for the initial testing of https://github.com/redhat-developer/rh-che/issues/860

### How have you tested this PR?
Not tested

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by garagatyi** [comment]
You can try to override `che.workspace.logs.root_dir=/workspace_logs` to something like `/tmp/workspace_logs` using env var `CHE_WORKSPACE_LOGS_ROOT__DIR`

**Comment by ibuziuk** [comment]
@garagatyi @rhopp Thanks for your help, guys. With dev cluster state it is currently impossible to get any input from che-server logs :/
@rhopp could you please tell how were you able to access the workspace events ?

**Comment by rhopp** [comment]
@ibuziuk All following PR checks failed before deployment to dev cluster - so the version currently deployed on dev cluster was from this PR - I just went to http://rhche-che6-automated.dev.rdu2c.fabric8.io/ (the link is allways the same) and tried that manually.

**Comment by ibuziuk** [comment]
@rhopp, ah so when tests are failing che-server deployment is not removed automatically, so it is possible to do some tests manually. Good to know.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Pull request closed without merging**
