### PR TITLE
Merge openshift-connector `stacks.json` with the one that is on master

### PR DESCRIPTION
**Pull request by davidfestal**
This fixes CHE-269

Signed-off-by: David Festal <dfestal@redhat.com>

### CODE REVIEW

**Comment by davidfestal** [comment]
I merged the `master` and `openshift-connector` branch (while making the required changes: removing the exec and ssh agents mainly), and add the content of the file to the new `stacks.json` on `rh-che`.

But I assume some still won't work correctly (such as the android stack I tested) since they eclipse docker requires a user with `sudo` rights.

@l0rd should we remove all the stacks that aren't supported in openshift.io (=> all the stacks that involve an `eclipse/xxx` docker image I assume) ?

**Comment by l0rd** [comment]
@davidfestal https://issues.jboss.org/browse/CHE-269 was more about fixing stacks.json in eclipse/che (and if necessary in redhat-developer/rh-che too):

> Currently [file stacks.json on branch openshift-connector-rebased](https://github.com/eclipse/che/blob/openshift-connector/ide/che-core-ide-stacks/src/main/resources/stacks.json) is identical (or pretty close) to master. But in [openshift-connector branch stacks.json](https://github.com/eclipse/che/blob/openshift-connector/ide/che-core-ide-stacks/src/main/resources/stacks.json) there are some differences that still need to be merged to the rebased branch. For example the stack "CentOS nodejs" only exist in openshift-connector and should be ported to openshift-connector-rebased.

**Comment by l0rd** [comment]
And yes `stacks.json` in rh-che should have:
- only supported stacks (java-centos, vertx, spring boot, nodejs-centos, wildfly, java-myslq-centos)
- the addition of the bayesian agent for every stack
- the removal of ssh agent for every stack

**Comment by davidfestal** [comment]
let me remove the additional non-rhche stacks and this should be OK then. right @l0rd ?

**Comment by davidfestal** [comment]
@l0rd 

>  But in openshift-connector branch stacks.json there are some differences (apart from `rhche` and agents) that still need to be merged to the rebased branch. For example the stack "CentOS nodejs" only exist in openshift-connector and should be ported to openshift-connector-rebased.

I reviewed the differences, and no significant difference exists now between the `openshift-connector` new RH-supported stacks in `rh-che` in the corresponding stacks in master (commit https://github.com/eclipse/che/commit/c8a8381b5d633b8e1115ee9df899d739cf16593e, just before PR https://github.com/eclipse/che/pull/5234). The reason is that some of our last changes in stacks were made as PR against master. And none is missing since @dharmit recently added the `Centos NodeJs` stack to master also.

**Comment by davidfestal** [comment]
@l0rd, @gorkem  is it OK for you also ?

**Pull request merged**
