### PR TITLE
move stacks to quay

### PR DESCRIPTION
**Pull request by riuvshin**
move stacks to quay
depends on: https://github.com/redhat-developer/che-dockerfiles/pull/43

needed for: https://jira.coreos.com/browse/APPSRE-127

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by riuvshin** [comment]
I've tested pulling speed from quay and devshift
```
1:29:15 PM    Normal    Pulled    Successfully pulled image "registry.devshift.net/che/centos_jdk8"
1:28:51 PM    Normal    Pulling    pulling image "registry.devshift.net/che/centos_jdk8"
```
vs
```
2:22:06 PM    Normal    Pulled    Successfully pulled image "quay.io/riuvshin/che-centos_jdk8"
2:21:46 PM    Normal    Pulling    pulling image "quay.io/riuvshin/che-centos_jdk8"
```

pulling from quay is a little bit faster from OSO

**Comment by rhopp** [comment]
Rh-che from this PR is deployed here: http://rhche-prcheck-956.devtools-dev.ext.devshift.net/dashboard
It's not able to start workspace as expected (because images are not yet pushed to quay). 
Once https://github.com/redhat-developer/che-dockerfiles/pull/43/files is merged&rebuilt we can test this PR again.

**Comment by riuvshin** [comment]
@rhopp yeah that is expected, thanks

**Comment by riuvshin** [comment]
[test]

**Comment by riuvshin** [comment]
@l0rd can we merge this?

**Comment by riuvshin** [comment]
@garagatyi @davidfestal ?

**Comment by davidfestal** [comment]
would it make sense to wait for after the upcoming Che hands-on lab ?
Or would it make the user experience better  ?

**Comment by l0rd** [comment]
I have merged it. It won't go to prod until we create a PR on saas-service anyway. But I would rather merge it as soon as possible because we have time to roll-it back if something goes wrong (unlikely) and it may help with tomorrow hands-on-lab. WDYT?

**Pull request merged**
