### PR TITLE
[WIP] Fixing test issues for 7.3.0

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Fix issues in tests to have 7.3.0 properly tested - https://github.com/redhat-developer/rh-che/issues/1640
Currently known issues to be fixed:
- [ ] Build&Run commands failing - a label of commands changed
- [ ] Artefacts are not archived - consequence of adding `set -e` to `.ci/cico_rhche_prcheck.sh`
- [ ] LS for Java Maven stack fails - investigating

### CODE REVIEW

**Comment by Katka92** [comment]
Last 2 times RH-Che was not deployed due to different reasons in events. Trying again.

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
The deploying of Postgres and RH-Che is failing. Closing and reopening this PR to have it run on in a new namespace.

**Pull request closed without merging**
