### PR TITLE
rh-che #785 - Updating upstream Che to 6.9.0

### PR DESCRIPTION
**Pull request by amisevsk**
- Update to `6.9.0`
- Fix license headers
- Fix build -- see commit `5935e4c`

### CODE REVIEW

**Comment by amisevsk** [comment]
Related: issue #785

**Comment by ibuziuk** [comment]
@rhopp @ScrewTSW che deployment on dev cluster seems to be broken - could you please take a look ?
https://ci.centos.org/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/380/console

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@amisevsk could you please rebase on the latest master and I believe we would be able to promote 6.9.0 to prod-preview

**Comment by amisevsk** [comment]
Rebased onto current master.

@rhopp sorry I didn't see your review before rebasing -- I can't see the comment anymore.

**Comment by ibuziuk** [comment]
@rhopp are you ok to merge and test 6.9.0 on prod-preview ?

**Pull request merged**
