### PR TITLE
Update to 7.16.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Upstream issue - https://github.com/eclipse/che/issues/17428
Tracking changes for fixing compatibility with upstream 7.16.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1935.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
@ibuziuk The only reason of pre-release test failure is Application not available issue. :+1:

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1935.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Pull request merged**
