### PR TITLE
Add env vars to allow usage of exec/terminal sidecar

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Changes the default RAM limit for sidecars to 256MB to overcome the issue that default RAM request in the cluster is bigger than default RAM limit set by Che. Proper fix from upstream will land later.
Sets env var with SA that should be used in all the workspaces to allow exec functionality from the workspace pods.
Since we still have an issue with JWT proxy memory limit it is needed to disable JWT proxy in a WS.NEXT workspace with https://github.com/eclipse/che/issues/11547#issuecomment-428128957. 

### What issues does this PR fix or reference?
Workarounds https://github.com/eclipse/che/issues/11547 till the proper fix https://github.com/eclipse/che/pull/11556 from upstream arrive. 
Related to https://github.com/redhat-developer/rh-che/issues/933

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
Workspace startup failed with 
```



Unrecoverable event occurred during workspace 'workspacenrohwrvs0c7buznt' startup: FailedMount, Unable to mount volumes for pod "workspacenrohwrvs0c7buznt.dockerimage-588855cfdd-7dxvj_rh-che-automation-preview-che(fc531fa1-d03f-11e8-91f8-02074d91bc8a)": timeout expired waiting for volumes to attach/mount for pod "rh-che-automation-preview-che"/"workspacenrohwrvs0c7buznt.dockerimage-588855cfdd-7dxvj". list of unattached/unmounted volumes=[claim-che-workspace], workspacenrohwrvs0c7buznt.dockerimage-588855cfdd-7dxvj
  | 2018-10-15 06:05:10,062[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 220]  - Failed to start Kubernetes runtime of workspace workspacenrohwrvs0c7buznt. Cause: Unrecoverable event occurred: 'FailedMount', 'Unable to mount volumes for pod "workspacenrohwrvs0c7buznt.dockerimage-588855cfdd-7dxvj_rh-che-automation-preview-che(fc531fa1-d03f-11e8-91f8-02074d91bc8a)": timeout expired waiting for volumes to attach/mount for pod "rh-che-automation-preview-che"/"workspacenrohwrvs0c7buznt.dockerimage-588855cfdd-7dxvj". list of unattached/unmounted volumes=[claim-che-workspace]', 'workspacenrohwrvs0c7buznt.dockerimage-588855cfdd-7dxvj'
```

I've cleaned PVC for the test account and trying to run PR check again.

**Comment by rhopp** [comment]
[test]

**Comment by garagatyi** [comment]
@rhopp thanks for restarting it and analysis! BTW do you know why we are having those issues with the PVC at the moment?

**Comment by garagatyi** [comment]
@l0rd I've just tested exec sidecar in this PR. The link to the deployed instance is above. Everything worked, but to make it work I needed:
- disable JWT proxy as we discussed in one of the issues you created (workpsace config attribute `"che.server.secure_exposer": "default"`)
-  decrease the amount of memory used by a machine from the workspace recipe. We have overall limit set to 3GB. Theia is set to use 2GB. Exec sidecar 256MB. So we have only 700+MB left for the recipe's machines and other sidecars. 
- restart a workspace a couple of times because of intermittent occurrence of `timeout expired waiting for volumes to attach/mount `

**Comment by l0rd** [comment]
@garagatyi cool :-) Ok to merge for me as well as #970. I will then add a stack for that (with a runtime with 256MB) and we are going to push everything to prod.

**Pull request merged**
