### PR TITLE
Update to 7.20.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.19.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by ScrewTSW** [comment]
[pre-release-tests]

**Comment by ScrewTSW** [comment]
[pre-release-tests]

**Comment by ScrewTSW** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk The build is failing on `Multi-Tenant Manager` part. We can not verify that pre-release tests are working correctly against this version (and can not fix new possible flakiness). Could you take a look, please?

**Comment by Katka92** [comment]
@tomgeorge @vparfonov Hi guys, there is some build issue, could you please take a look at that? Thank you

**Comment by Katka92** [comment]
@ibuziuk Great! You fixed that! Now it is failing on code incompatibility - I'll fix that by tomorrow morning.

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by jmelis** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Hi, now the check is failing on compilation error. Will you have time to take a look?

**Comment by Katka92** [comment]
@ibuziuk Thank you for the fix, now we are failing on https://github.com/eclipse/che/issues/18075

**Comment by ibuziuk** [comment]
@Katka92 yeah, commented in the upstream issue - https://github.com/eclipse/che/issues/18075#issuecomment-705487253

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW could you please take a look at the failing test:

```
11 passing (4m)
  1 failing

  1) Java Maven test
       Validation of workspace build and run
         Run command 'maven build':
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/tmp/rh-che/local_tests/node_modules/e2e/dist/tests/devfiles/JavaMaven.spec.js)
```

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
The test running `build` command was skipped in upstream. It seems it is not propagated here. We'll check that.

**Comment by Katka92** [comment]
So, the root cause is that the upstream nightly test image was not updated for 4 days, the reason is `FATAL: Vault credentials not found for 'devtools-osio-ci/quay-eclipse-che-credentials'`. So we don't have the latest changes in place and we can not test that properly.

**Comment by Katka92** [comment]
The image was updated manually, re-running the tests.
[test]

**Pull request merged**
