### PR TITLE
rh-che #1347 Adding Che 7 java-maven upstream stack

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Adding Che 7 java-maven upstream stack

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/1347

### How have you tested this PR?
Tested on che.openshift.io
Basic example console java example works just fine.
However, having problems with running `vertx-http-booster`
"Build" command works just fine, but "Run" command fails with the following error and preview URL is not working correctly:

> [INFO] SEVERE: Failed to create the vert.x instance
> [INFO] java.lang.IllegalStateException: Failed to create cache dir
> [INFO]  at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:333)
> [INFO]  at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:88)
> [INFO]  at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:168)
> [INFO]  at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
> [INFO]  at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
> [INFO]  at io.vertx.core.Vertx.vertx(Vertx.java:85)
> [INFO]  at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
> [INFO]  at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:276)
> [INFO]  at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:191)
> [INFO]  at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
> [INFO]  at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
> [INFO]  at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
> [INFO]  at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
> [INFO]  at io.vertx.core.Launcher.main(Launcher.java:45)

Looks like the community image is not fully compatible with OpenShift.

### CODE REVIEW

**Comment by ibuziuk** [comment]
We could probably merge this PR even though not all the samples would work and try to address the follow up issue in the next sprint - https://github.com/eclipse/che/issues/13383

**Comment by ibuziuk** [comment]
btw, `spring-boot-gs-rest-service` seems to work just fine.

**Comment by ibuziuk** [comment]
@amisevsk thank you for detailed review. Do you happen to know if the same issues present on minishift?
wdyt, should we merge the current PR and create follow up issues related to the stack and try to address as part of the https://github.com/redhat-developer/rh-che/issues/1347 ?

**Comment by amisevsk** [comment]
@ibuziuk I think the same problems are present whenever running on OpenShift, but haven't confirmed. We've thus far made the modifications in the redhat-developer `che-dockerfiles` repo to avoid them. 

I'm +1 on merging this PR since it mostly works, so long as we realize there's going to be more to do on this stack in the future.

**Pull request merged**
