### PR TITLE
Increasing memory limit to 1.5Gi for rh-che

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Increasing memory limit to 1.5Gi for rh-che

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/901

### How have you tested this PR?
Not tested

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by pbergene** [comment]
As it's only running one replica (?) this is a net increase of 750MB - I think we should be ok, but let me verify this.  When / if we go to multiple replicas we can re-visit into what makes sense.

**Comment by ibuziuk** [comment]
[test]

**Comment by pbergene** [comment]
4-5G free on rh-idev for the entire cluster..  will have to keep an eye on that.  Starting to cut it close on dsaas, but a few nodes worth left.  +1 to this.

**Comment by ibuziuk** [comment]
@pbergene thanks for confirmation

**Comment by pbergene** [comment]
@ibuziuk Thanks for running it by us :+1:

**Comment by rhopp** [comment]
@pbergene The URL reported back to github is not fixed yet (after dev cluster reinstallation). The correct URL is http://rhche-che6-automated.devtools-dev.ext.devshift.net

**Comment by l0rd** [comment]
@ibuziuk we need to answer the following questions:

1. How can we reproduce the OOM? Starting hundreds of simultaneous workspaces is enough?
2. What is the OOM root cause? What classes/methods are using more memory?
3. With 1.5G memory limit what's the maximum number of simultaneous workspaces Che is able to serve?

**Comment by ibuziuk** [comment]
@l0rd I have added the last comment as a subtask for https://github.com/redhat-developer/rh-che/issues/898

**Comment by l0rd** [comment]
great thank you @ibuziuk

**Pull request merged**
