### PR TITLE
[WIP] Testing and stabilising pre-release tests

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Test pre-release test suite and disable unstable tests.

### CODE REVIEW

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io/
[pre-release-tests]

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io/
[pre-release-tests]

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io
[pre-release-tests]

**Comment by Katka92** [comment]
https://che.prod-preview.openshift.io
[pre-release-tests]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
@Katka92 does it makes sense to close this PR and do the verification against https://github.com/openshiftio/saas-openshiftio/pull/1454 (I believe we discussed last time that those dummy PRs are antipattern)

**Comment by Katka92** [comment]
During this PR I found out some issues. Those issues will be fixed upstream. Closing.

**Pull request closed without merging**
