### PR TITLE
Update to 7.26.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Tracking changes for fixing compatibility with upstream 7.26.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

Related issue - https://github.com/eclipse/che/issues/18965

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2043.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2043.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by Katka92** [comment]
https://rhche-prcheck-2043.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2043.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2043.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-2043.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
```
Killed by signal 15.
+ rtn_code=124
+ '[' 124 -eq 0 ']'
+ [[ 124 -eq 124 ]]
+ echo 'BUILD TIMEOUT'
BUILD TIMEOUT
+ cico node done 7a5b9b28
```
@ScrewTSW @Katka92  promoting to stg, but we need to fix the pre-release test-suite before promoting to production

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
