### PR TITLE
Adapt to new plugin notation

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Do not merge until PR https://github.com/eclipse/che/pull/13204 is in the version of upstream RhChe uses.
Note: this PR doesn't adapt resources prefetcher by @davidfestal

### CODE REVIEW

**Comment by ibuziuk** [comment]
@amisevsk @davidfestal could you please review?

**Comment by ibuziuk** [comment]
@amisevsk it looks like you have already done all the required changes and this PR can be safely closed, right?

**Comment by ibuziuk** [comment]
probably we can just import the doc changes in `dev-guide.adoc`

**Comment by amisevsk** [comment]
@ibuziuk Yeah I didn't notice this PR and reproduced a few of the changes. The dev-guide changes are still great to merge though.

**Comment by amisevsk** [comment]
Created https://github.com/redhat-developer/rh-che/pull/1407

**Comment by ibuziuk** [comment]
Thank you @amisevsk 
I believe now we can safely close this PR

**Pull request closed without merging**
