### PR TITLE
Update to 7.18.0

### PR DESCRIPTION
**Pull request by RhCheGithubBot**
Upstream issue - https://github.com/eclipse/che/issues/17706

Tracking changes for fixing compatibility with upstream 7.18.0-SNAPSHOT. This PR was created automatically by Jenkins from job devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by Katka92** [comment]
@ibuziuk Hello, the build is failing on `Multi-Tenant Manager` part. Could you take a look, please?

<details>
<summary>Compilation error</summary>

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /root/payload/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/RhCheInfraEnvironmentProvisioner.java:[104,5] constructor OpenShiftEnvironmentProvisioner in class org.eclipse.che.workspace.infrastructure.openshift.OpenShiftEnvironmentProvisioner cannot be applied to given types;
  required: boolean,org.eclipse.che.workspace.infrastructure.openshift.provision.OpenShiftUniqueNamesProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisionerProvider<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>,org.eclipse.che.workspace.infrastructure.kubernetes.provision.server.ServersConverter<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>,org.eclipse.che.workspace.infrastructure.kubernetes.provision.env.EnvVarsConverter,org.eclipse.che.workspace.infrastructure.kubernetes.provision.restartpolicy.RestartPolicyRewriter,org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.WorkspaceVolumesStrategy,org.eclipse.che.workspace.infrastructure.kubernetes.provision.limits.ram.ContainerResourceProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.LogsVolumeMachineProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.PodTerminationGracePeriodProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.ImagePullSecretProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.ProxySettingsProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.NodeSelectorProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.AsyncStorageProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.AsyncStoragePodInterceptor,org.eclipse.che.workspace.infrastructure.kubernetes.provision.ServiceAccountProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.CertificateProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.SshKeysProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.GitConfigProvisioner,org.eclipse.che.workspace.infrastructure.openshift.server.OpenShiftPreviewUrlExposer,org.eclipse.che.workspace.infrastructure.kubernetes.provision.VcsSslCertificateProvisioner
  found: boolean,org.eclipse.che.workspace.infrastructure.openshift.provision.OpenShiftUniqueNamesProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisionerProvider<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>,org.eclipse.che.workspace.infrastructure.kubernetes.provision.server.ServersConverter<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>,org.eclipse.che.workspace.infrastructure.kubernetes.provision.env.EnvVarsConverter,org.eclipse.che.workspace.infrastructure.kubernetes.provision.restartpolicy.RestartPolicyRewriter,org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.WorkspaceVolumesStrategy,org.eclipse.che.workspace.infrastructure.kubernetes.provision.limits.ram.ContainerResourceProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.LogsVolumeMachineProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.PodTerminationGracePeriodProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.ImagePullSecretProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.ProxySettingsProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.AsyncStorageProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.AsyncStoragePodInterceptor,org.eclipse.che.workspace.infrastructure.kubernetes.provision.ServiceAccountProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.CertificateProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.SshKeysProvisioner,org.eclipse.che.workspace.infrastructure.kubernetes.provision.GitConfigProvisioner,org.eclipse.che.workspace.infrastructure.openshift.server.OpenShiftPreviewUrlExposer,org.eclipse.che.workspace.infrastructure.kubernetes.provision.VcsSslCertificateProvisioner
  reason: actual and formal argument lists differ in length

</details>

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Comment by ibuziuk** [comment]
https://rhche-prcheck-1962.apps.che-dev.x6e0.p1.openshiftapps.com
[pre-release-tests]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
