### PR TITLE
Update Che version to 6.8.0

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by rhopp** [comment]
[test]

**Comment by ibuziuk** [comment]
@amisevsk yeah, we want to promote 6.8.0 on prod-preview only for now. For prod we will wait for the patch `6.8.1` with regressions fixed ;-)

**Comment by ibuziuk** [comment]
going to merge it after https://github.com/redhat-developer/rh-che/issues/726 would be fixed

**Comment by ibuziuk** [comment]
[test]

**Pull request merged**
