### PR TITLE
Che6 on OSIO

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This PR contains changes that are required to be able to run RH Che on OSIO.
It's much easier to review PR commit by commit.
List of changes that are made:
- Added importing dependency managment from che-parent;
- Updated assembly-wsmaster-war;
- Updated assembly-wsagent-war module;
- Removed outdated workspace-logging-override module (che6 doesn't have an API for storing/retrieving machines and agents logs). Here is an issue to provide an ability to override agents logs dir https://github.com/eclipse/che/issues/7807. When this issue will be fixed, I think overriding of logs dirs will be performed by configuration properties;
- Moved WorkspaceSubjectsRegistry from eclipse/che#master for BayesianTokenProvider;
- Updated fabric8-multi-tenant-manager module. Added OpenShiftClientFactory and OpenShiftProjectFactory which will provide different workspace environment configuration according to a current user.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7155

Depends on ~~https://github.com/eclipse/che/pull/7604~~

### How have you tested this PR?
Yes. Rh Che Server was deployed on https://dev.rdu2c.fabric8.io:8443/, workspaces start successfully
<details>
<summary>Workspace start demo</summary>

rh-che6
</details>

<details>
<summary>Deploying rh-che with PR changes</summary>

It's deployed with [deploy_che.sh](https://github.com/eclipse/che/blob/che6/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh) script from Che repository. It is needed to specify the following configuration parameters for deploying rh-che 
```
# Deploy rh-che based on che6
# https://dev.rdu2c.fabric8.io:8443/
export OPENSHIFT_FLAVOR=ocp

export CHE_IMAGE_REPO="sleshchenko/che-server"
export CHE_IMAGE_TAG="nightly-fabric8"

export CHE_MULTIUSER=true
export CHE_DEDICATED_KEYCLOAK=false

export CHE_OPENSHIFT_PROJECT=che6-server

export OPENSHIFT_ROUTING_SUFFIX=dev.rdu2c.fabric8.io
export OPENSHIFT_TOKEN={TOKEN_HERE}
export OPENSHIFT_ENDPOINT=https://dev.rdu2c.fabric8.io:8443
export ENABLE_SSL=false

export CHE_INFRA_OPENSHIFT_PVC_STRATEGY="common"

export IMAGE_PULL_POLICY=Always
```
</details>

### CODE REVIEW

**Comment by benoitf** [comment]
> Removed outdated workspace-logging-override module (che6 doesn't have an API for storing/retrieving machines and agents logs)

at first sight, it looks odd to remove that part as it was introduced for OSIO

**Comment by sleshchenko** [comment]
This module doesn't have any chance to work on che6 because it doesn't have such functionality. If it is required for OSIO, It is needed to create an issue in Che repository. 
@benoitf Do you know if it is needed just to store agents logs in configured PVC folder or have an API for retrieving this logs?

**Comment by benoitf** [comment]
@sleshchenko I would say that it's mainly for having logs in PVC. (And external tools may use that path to grab the logs from PVC)

**Comment by sleshchenko** [comment]
@benoitf I'll take a look if it is possible to override logs dir in che6 and create an issue for that or fix it in the scope of the current PR. Thanks for the nice catch.

**Comment by benoitf** [comment]
@sleshchenko I think it's only requiring a subset of https://github.com/eclipse/che/pull/6738

**Comment by sleshchenko** [comment]
@benoitf Thanks for sharing.
So I'd say that this PR contains changes that are required for the initial state of rh-che and all missed features, overrides should be fixed in other issues not to make this PR so huge and make changes review easier.
I'll take a look David's PR and create issues for missed parts.

**Comment by sleshchenko** [comment]
@davidfestal @ibuziuk @l0rd Please take a look.

**Pull request merged**
