### PR TITLE
Update upstream dependency to 6.15.0

### PR DESCRIPTION
**Pull request by amisevsk**
Tracking branch for next release. Plan is to rebase onto rhche master every Friday and make sure build works.

### CODE REVIEW

**Comment by rhopp** [comment]
@ibuziuk There was an error on dev cluster yesterday: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2438#note_476645
Hopefully it's fixed today (havent tried that yet)

[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by amisevsk** [comment]
@ibuziuk Looks like https://github.com/eclipse/che/pull/10128 broke the build. I can take a look at it tomorrow.

**Comment by ibuziuk** [comment]
@amisevsk there are quite a few `yaml` files in the PR e.g. `broker-configmap.yaml`. were those committed accidentally ?

**Comment by amisevsk** [comment]
@ibuziuk They sure were :)

Leftover files from testing earlier work. Thanks for catching that.

**Comment by ibuziuk** [comment]
@amisevsk `6.15.0` has been released so we are ready to remove WIP / snapshot from the PR ;-)

**Pull request merged**
